import type { BlockType } from "./types";

export type ButtonField = { label: string; url: string; variant: "primary" | "secondary" | "outline" | "ghost"; color?: string; textColor?: string };
export type LinkField = { label: string; url: string };

export const DEFAULT_FIELDS: Record<Exclude<BlockType, "layout">, Record<string, unknown>> = {
  "nav-simple": {
    logoImage: "",
    logoText: "Acme",
    cta: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
    ctaSecondary: { label: "Log in", url: "#", variant: "ghost" } as ButtonField,
    links: [
      { label: "Home", url: "#" },
      { label: "About", url: "#" },
      { label: "Pricing", url: "#" },
    ] as LinkField[],
  },
  "nav-centered": {
    logoImage: "",
    logoText: "Acme",
    links: [
      { label: "Home", url: "#" },
      { label: "Features", url: "#" },
      { label: "Pricing", url: "#" },
      { label: "Contact", url: "#" },
    ] as LinkField[],
  },
  "footer-simple": {
    logoImage: "",
    logoText: "Acme",
    copyright: "© 2025 Acme Inc.",
    links: [
      { label: "Privacy", url: "#" },
      { label: "Terms", url: "#" },
      { label: "Contact", url: "#" },
    ] as LinkField[],
  },
  "footer-columns": {
    logoImage: "",
    logoText: "Acme",
    tagline: "Build better websites.",
    copyright: "© 2025 Acme Inc.",
    col1Title: "Product",
    col1Links: [
      { label: "Features", url: "#" },
      { label: "Pricing", url: "#" },
      { label: "Docs", url: "#" },
    ] as LinkField[],
    col2Title: "Company",
    col2Links: [
      { label: "About", url: "#" },
      { label: "Blog", url: "#" },
      { label: "Careers", url: "#" },
    ] as LinkField[],
    col3Title: "Legal",
    col3Links: [
      { label: "Privacy", url: "#" },
      { label: "Terms", url: "#" },
      { label: "Cookies", url: "#" },
    ] as LinkField[],
  },
  "hero-centered": {
    headline: "Build beautiful websites",
    subtext: "No code required. Launch in minutes.",
    primaryCta: { label: "Start free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "See demo", url: "#", variant: "outline" } as ButtonField,
    bgImage: "",
  },
  "hero-split": {
    headline: "Launch faster than ever",
    subtext: "Ship production-ready pages without writing code.",
    cta: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
    image: "",
    imageRight: true,
  },
  "features-3col": {
    title: "Why choose us",
    subtext: "Everything you need to build and grow.",
    features: [
      { icon: "⚡", title: "Lightning fast", description: "Build pages in seconds." },
      { icon: "🎨", title: "Beautiful design", description: "Stunning templates included." },
      { icon: "🔧", title: "Customizable", description: "Tweak every pixel." },
    ],
  },
  "features-4col": {
    title: "Everything you need",
    subtext: "Powerful features to ship faster.",
    features: [
      { icon: "⚡", title: "Fast", description: "Lightning quick performance." },
      { icon: "🎨", title: "Beautiful", description: "Designed with care." },
      { icon: "🔧", title: "Flexible", description: "Customize anything." },
      { icon: "🚀", title: "Scalable", description: "Grows with your team." },
    ],
  },
  "text-image": {
    headline: "A better way to build",
    subtext: "Pair powerful tools with a beautiful interface that scales with your team.",
    image: "",
    imageRight: true,
  },
  "stats-bar": {
    stats: [
      { number: "10,000", label: "Users", prefix: "", suffix: "+" },
      { number: "99.9", label: "Uptime", prefix: "", suffix: "%" },
      { number: "50", label: "Countries", prefix: "", suffix: "+" },
      { number: "24/7", label: "Support", prefix: "", suffix: "" },
    ],
  },
  testimonials: {
    items: [
      { quote: "This product changed how our team ships.", author: "Jane Doe", role: "CEO, Company", avatar: "" },
      { quote: "Best decision we made this year.", author: "John Smith", role: "CTO, Startup", avatar: "" },
      { quote: "I can't imagine working without it.", author: "Alex Lee", role: "PM, Agency", avatar: "" },
    ],
  },
  "logo-grid": {
    title: "Trusted by leading teams",
    logos: Array.from({ length: 6 }).map((_, i) => ({ src: "", alt: `Logo ${i + 1}` })),
  },
  "cta-banner": {
    headline: "Ready to get started?",
    subtext: "Join thousands of teams already building with PageBuilder.",
    button: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
  },
  faq: {
    title: "Frequently asked questions",
    items: [
      { question: "How does it work?", answer: "Sign up and start building in minutes." },
      { question: "Is there a free plan?", answer: "Yes, our free plan includes core features." },
      { question: "Can I cancel anytime?", answer: "Absolutely — no contracts." },
      { question: "Do you offer support?", answer: "24/7 support on all paid plans." },
    ],
  },
  "blog-preview": {
    title: "From our blog",
    subtitle: "Thoughts, ideas, and insights from our team.",
    count: 3,
    ctaLabel: "View all posts",
    ctaUrl: "/blog",
  },
  "hero-gradient": {
    badge: "✦ New — AI-powered platform",
    headline: "Build faster with\nless friction",
    subtext: "The modern platform that helps teams ship products 2× faster. Loved by 10,000+ companies.",
    primaryCta: { label: "Start free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "See demo", url: "#", variant: "ghost" } as ButtonField,
    image: "",
  },
  "hero-centered-image": {
    badge: "Trusted by 10,000+ teams",
    headline: "The website builder\nyour team will love",
    subtext: "Design beautiful pages without writing code. Publish in minutes.",
    primaryCta: { label: "Get started free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "View demo", url: "#", variant: "outline" } as ButtonField,
    image: "https://placehold.co/1200x600/f1f5f9/94a3b8?text=Product+Screenshot",
  },
  "features-alternating": {
    title: "Everything you need to grow",
    subtext: "Powerful features built for modern teams",
    items: [
      { tag: "Design", title: "Drag-and-drop page builder", description: "Create stunning pages visually. No design skills needed. Hundreds of ready-made blocks.", image: "https://placehold.co/600x400/eff6ff/3b82f6?text=Feature+1", ctaLabel: "Learn more", ctaUrl: "#" },
      { tag: "Performance", title: "Blazing fast by default", description: "Every page is automatically optimised for Core Web Vitals. Your visitors get instant load times.", image: "https://placehold.co/600x400/f0fdf4/22c55e?text=Feature+2", ctaLabel: "Learn more", ctaUrl: "#" },
      { tag: "Analytics", title: "Built-in analytics dashboard", description: "See who visits your site, where they come from, and what they do. No third-party tools needed.", image: "https://placehold.co/600x400/fdf4ff/a855f7?text=Feature+3", ctaLabel: "Learn more", ctaUrl: "#" },
    ],
  },
  "features-icon-cards": {
    title: "Why teams choose us",
    subtext: "Built for speed, designed for scale",
    columns: 3,
    features: [
      { icon: "⚡", iconBg: "#eff6ff", title: "Lightning fast", description: "Pages load in under 200ms with our global CDN." },
      { icon: "🎨", iconBg: "#fdf4ff", title: "Beautiful templates", description: "50+ professionally designed templates to start from." },
      { icon: "🔒", iconBg: "#f0fdf4", title: "Enterprise security", description: "SOC2 compliant with 99.9% uptime SLA." },
      { icon: "📊", iconBg: "#fff7ed", title: "Smart analytics", description: "Understand your audience with built-in insights." },
      { icon: "🤝", iconBg: "#fef2f2", title: "Team collaboration", description: "Work together in real-time with live cursors." },
      { icon: "🔌", iconBg: "#f8fafc", title: "Integrations", description: "Connect with 100+ tools you already use." },
    ],
  },
  "pricing-modern": {
    title: "Simple, transparent pricing",
    subtext: "No hidden fees. Cancel anytime.",
    plans: [
      { name: "Starter", price: "$0", period: "/month", description: "Perfect for personal projects", highlighted: false, features: ["5 pages", "Custom domain", "Basic analytics", "Community support"], cta: { label: "Get started", url: "#", variant: "outline" } },
      { name: "Pro", price: "$29", period: "/month", description: "For growing businesses", highlighted: true, features: ["Unlimited pages", "Custom domain", "Advanced analytics", "Priority support", "Remove branding", "A/B testing"], cta: { label: "Start free trial", url: "#", variant: "primary" } },
      { name: "Enterprise", price: "$99", period: "/month", description: "For large teams", highlighted: false, features: ["Everything in Pro", "SSO / SAML", "Dedicated support", "Custom contracts", "SLA guarantee", "On-premise option"], cta: { label: "Contact sales", url: "#", variant: "outline" } },
    ],
  },
  "testimonials-wall": {
    title: "Loved by thousands of teams",
    items: [
      { quote: "This builder saved us months of development time. Our marketing team now ships landing pages independently.", author: "Sarah Chen", role: "Head of Marketing", company: "Acme Corp", stars: 5 },
      { quote: "The templates are absolutely beautiful. We went from zero to live website in one afternoon.", author: "Marcus Williams", role: "Founder", company: "BuildFast", stars: 5 },
      { quote: "Finally a no-code tool that doesn't feel like a compromise. Our dev team actually approves.", author: "Priya Patel", role: "CTO", company: "ScaleUp", stars: 5 },
      { quote: "We cut our web production costs by 60%. The ROI was immediate.", author: "James Liu", role: "VP Product", company: "GrowthCo", stars: 5 },
      { quote: "Best page builder I've used in 10 years. The AI suggestions are a game changer.", author: "Elena Rodriguez", role: "Designer", company: "Studio R", stars: 5 },
      { quote: "Our conversion rate went up 34% after rebuilding our landing page with this tool.", author: "Tom Bergmann", role: "Growth Lead", company: "Fintech Inc", stars: 5 },
    ],
  },
  "team-grid": {
    title: "Meet the team",
    subtext: "The people building the future of web design",
    members: [
      { name: "Alex Johnson", role: "CEO & Co-founder", avatar: "https://placehold.co/300x300/e0e7ff/4f46e5?text=AJ", linkedin: "#" },
      { name: "Maria Garcia", role: "Head of Design", avatar: "https://placehold.co/300x300/fce7f3/db2777?text=MG", linkedin: "#" },
      { name: "David Kim", role: "Lead Engineer", avatar: "https://placehold.co/300x300/d1fae5/059669?text=DK", linkedin: "#" },
      { name: "Sarah Brown", role: "Head of Product", avatar: "https://placehold.co/300x300/fef3c7/d97706?text=SB", linkedin: "#" },
    ],
  },
  "stats-bold": {
    title: "Trusted by teams worldwide",
    stats: [
      { number: "50K", suffix: "+", label: "Active users" },
      { number: "99.9", suffix: "%", label: "Uptime SLA" },
      { number: "2×", suffix: "", label: "Faster launches" },
      { number: "4.9", suffix: "★", label: "Average rating" },
    ],
  },
  "steps-process": {
    title: "Get started in minutes",
    subtext: "No credit card required",
    steps: [
      { number: "01", title: "Create your account", description: "Sign up free in 30 seconds. No credit card needed." },
      { number: "02", title: "Choose a template", description: "Pick from 50+ professionally designed templates." },
      { number: "03", title: "Customise & publish", description: "Edit content, add your brand, and go live instantly." },
    ],
  },
  "cta-banner-gradient": {
    headline: "Ready to build something amazing?",
    subtext: "Join 50,000+ teams already using our platform. Free forever for small teams.",
    primaryCta: { label: "Start for free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "Talk to sales", url: "#", variant: "ghost" } as ButtonField,
  },
  "hero-salescode": {
    badge: "World's First AI Native Platform for CPG Sales",
    title: "All your CPG Sales on One Platform.",
    description: "Build your SFA, DMS, eB2B and AI agents...",
    ctaText: "Build Your Stack",
    ctaUrl: "#product-selection",
  },
  "impact-salescode": {
    title: "Business Impact Guaranteed\nwith AI for SFA and eB2B for CPG Sales",
    videoUrl: "https://salescode.ai/wp-content/uploads/2025/09/flow-animaiton-solution-to-deployment3.mp4",
    stats: [
      { value: "35", suffix: "%", description: "Reduction in Cost-to-Serve" },
      { value: "18", suffix: "%", description: "Increase in Distribution" },
      { value: "5", suffix: "%", description: "Reduction in Daily Sales Loss" },
      { value: "3", suffix: "x", description: "Minimum Sales Uplift" },
    ],
  },
  "clients-salescode": {
    title: "Privileged to work with Top CPG Brands",
    sectionId: "cpg-brands",
  },
  "security-salescode": {
    heading: "Your Data is Safe with Us",
    certs: [
      { url: "https://salescode.ai/wp-content/uploads/2025/09/GDPR-1-r23yrj45d5eecfx8318k9wj5vikzl0sfdvoueb8d4w.webp", alt: "GDPR" },
      { url: "https://salescode.ai/wp-content/uploads/2025/09/ISO-1-r23yqigfym07rneh13e42ns6phlo8tqw8u8woiqpvk.webp", alt: "ISO 27001" },
      { url: "https://salescode.ai/wp-content/uploads/2025/09/SOC-1-r23ytr0fi2frrap64hrunudcd9n6ralm0v546txwg0.webp", alt: "SOC 2 Type 2" },
    ],
  },
  "experience-video-salescode": {
    videoUrl: "https://salescode.ai/wp-content/uploads/2025/09/experience-center-vid-for-website-video2.mp4",
    title: "SalesCode Experience Center",
    subtitle: "Experience the 'Code of Future-Ready Sales Teams & Trade'",
    linkText: "",
    linkUrl: "",
  },
  "cta-salescode": {
    badge: "Ready to Deploy",
    heading: "Ready to build your AI-powered sales platform?",
    subtext: "Start with SFA, DMS, or eB2B — or combine all three with SCAI. Go live in weeks with guaranteed, contractual results.",
    ctaText: "Build Your Stack →",
    ctaUrl: "#product-selection",
  },
  "navbar-salescode-slot": {
    bgColor: "",
    links: [
      { label: "About Us",   href: "/about" },
      { label: "Clients",    href: "/clients" },
      { label: "Blogs",      href: "/blog" },
      { label: "Contact Us", href: "/contact-us" },
    ],
  },
  "product-selection-slot": {},
  "platform-features-slot": {},
  "integrations-slot": {},
  "blogs-section-slot": {},
  "footer-salescode-slot": {},
  "about-page-slot": {},
  "clients-page-slot": {},
  "contact-page-slot": {},
  "blog-page-slot": {},
  'slick-hero-split': {
    badge: "New · Spring release",
    headlineStart: "Run your whole business on",
    headlineAccent: "one platform",
    headlineEnd: "your team will actually love.",
    subtitle: "From CRM to invoicing, inventory to email campaigns — replace twelve tools with one beautifully integrated suite.",
    primaryCtaLabel: "Start free — no card",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Watch 2-min demo",
    secondaryCtaHref: "#demo",
    mockupImageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80",
    trustLabel: "Trusted by 7M+ users worldwide",
  },
  'slick-hero-video': {
    eyebrow: "★ FEATURED IN TECHCRUNCH",
    headlineTop: "The operating system",
    headlineAccent: "for modern",
    headlineBottom: "businesses.",
    subtitle: "Beautifully designed apps that work together out of the box. Built for teams that ship.",
    primaryCtaLabel: "Get started — it's free",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Talk to sales",
    secondaryCtaHref: "#sales",
    videoPoster: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&q=80",
    videoSrc: "",
    metrics: [
      { value: "4.9/5", label: "G2 rating" },
      { value: "12k+", label: "Active teams" },
      { value: "99.99%", label: "Uptime" },
    ],
  },
  'slick-features-bento': {
    eyebrow: "★ FEATURES",
    heading: "Everything you need.",
    headingAccent: "Nothing you don't.",
    subheading: "A focused toolkit that scales from your first hire to your first IPO.",
    features: [
      { icon: "⚡", title: "Realtime sync", description: "Every change reflected in under 200 ms across all devices.", tone: "lime", span: "md" },
      { icon: "🔒", title: "SOC 2 Type II", description: "Enterprise security built in, not bolted on.", tone: "violet", span: "sm" },
      { icon: "🤖", title: "AI inbox", description: "Triage, draft replies, and close tickets in seconds.", tone: "amber", span: "lg" },
      { icon: "📊", title: "Live dashboards", description: "Drag-and-drop analytics that update in real time.", tone: "pink", span: "sm" },
      { icon: "🌍", title: "Global edge", description: "Deployed to 200+ PoPs for sub-10 ms response anywhere.", tone: "sky", span: "md" },
      { icon: "🔌", title: "100+ integrations", description: "Connect your existing stack in one click.", tone: "ink", span: "md" },
    ],
  },
  'slick-features-alternating': {
    rows: [
      { tag: "PLANNING", headline: "Plan your", headlineAccent: "entire roadmap", description: "From epics to sub-tasks, structure your work exactly the way your team thinks.", bullets: ["Nested tasks with dependencies", "Custom fields and workflows", "Milestone tracking"], ctaLabel: "See planning features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80", accent: "lime" },
      { tag: "BUILDING", headline: "Ship code", headlineAccent: "with confidence", description: "Git-native project tracking that keeps engineers in flow and managers informed.", bullets: ["Branch-to-issue linking", "Auto-close on merge", "PR review queues"], ctaLabel: "See dev features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80", accent: "violet" },
      { tag: "SHIPPING", headline: "Release with", headlineAccent: "zero drama", description: "One-click deployments, staged rollouts, and instant rollback — all from your dashboard.", bullets: ["Feature flags built-in", "Canary releases", "One-click rollback"], ctaLabel: "See shipping features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80", accent: "amber" },
    ],
  },
  'slick-pricing': {
    eyebrow: "★ PRICING",
    heading: "One price.",
    headingAccent: "Everything included.",
    subheading: "No seat fees. No hidden add-ons. Cancel any time.",
    currency: "$",
    plans: [
      { name: "Starter", description: "Perfect for solo makers and early-stage startups.", monthlyPrice: 0, annualPrice: 0, features: ["Up to 3 projects", "5 team members", "1 GB storage", "Community support"], ctaLabel: "Get started free", ctaHref: "#start", highlighted: false },
      { name: "Growth", description: "Built for teams moving fast and shipping often.", monthlyPrice: 29, annualPrice: 24, features: ["Unlimited projects", "25 team members", "50 GB storage", "Priority support", "Advanced analytics", "Custom domains"], ctaLabel: "Start 14-day trial", ctaHref: "#trial", highlighted: true, badge: "Most popular" },
      { name: "Enterprise", description: "For organizations that need security and scale.", monthlyPrice: 99, annualPrice: 79, features: ["Everything in Growth", "Unlimited members", "SSO & SAML", "Audit logs", "99.99% SLA", "Dedicated success manager"], ctaLabel: "Talk to sales", ctaHref: "#sales", highlighted: false },
    ],
  },
  'slick-testimonials-carousel': {
    eyebrow: "★ LOVED BY TEAMS",
    heading: "Twelve thousand teams",
    headingAccent: "can't be wrong.",
    testimonials: [
      { quote: "Switching to Atlas was the best decision we made all year. Our sprint velocity doubled in the first month.", rating: 5, name: "Sarah Chen", role: "VP Engineering", company: "Stripe", avatarUrl: "https://i.pravatar.cc/120?img=1" },
      { quote: "We replaced Jira, Confluence, and Notion with Atlas. Same features, one tenth the complexity.", rating: 5, name: "Marcus Hill", role: "CTO", company: "Vercel", avatarUrl: "https://i.pravatar.cc/120?img=2" },
      { quote: "The AI triage alone saves my support team 4 hours every day. I'd never go back.", rating: 5, name: "Priya Nair", role: "Head of Customer Success", company: "Linear", avatarUrl: "https://i.pravatar.cc/120?img=3" },
      { quote: "Onboarding took 20 minutes. That's unheard of for enterprise software.", rating: 5, name: "Tom Briggs", role: "Director of Ops", company: "Shopify", avatarUrl: "https://i.pravatar.cc/120?img=4" },
    ],
  },
  'slick-testimonials-logos': {
    eyebrow: "★ TRUSTED AT EVERY STAGE",
    heading: "From seed to",
    headingAccent: "S&P 500.",
    logos: [
      { name: "Stripe", src: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg" },
      { name: "Notion", src: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png" },
      { name: "Figma", src: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
      { name: "Vercel", src: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico" },
      { name: "Shopify", src: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Shopify_logo_2018.svg" },
      { name: "Loom", src: "https://i.pravatar.cc/40?img=10" },
    ],
    quote: "Atlas is the rare tool that made our team faster without adding process. It just gets out of the way.",
    authorName: "Elena Park",
    authorRole: "Director of Engineering",
    authorCompany: "Loom",
    authorAvatarUrl: "https://i.pravatar.cc/120?img=49",
  },
  'slick-stats': {
    eyebrow: "★ BY THE NUMBERS",
    heading: "Built for scale.",
    headingAccent: "Trusted at scale.",
    description: "Five years obsessing over performance and developer experience — and the numbers show it.",
    stats: [
      { value: "12,400", suffix: "+", label: "Teams worldwide" },
      { value: "99.99", suffix: "%", label: "Uptime guaranteed" },
      { value: "3.2", suffix: "x", label: "Faster cycle time" },
      { value: "48", suffix: "M", label: "Issues shipped" },
    ],
  },
  'slick-faq': {
    eyebrow: "★ FAQ",
    heading: "Questions,",
    headingAccent: "answered.",
    subheading: "Can't find what you're looking for? Reach out — we usually reply within an hour.",
    items: [
      { category: "Billing", question: "Is there a free plan?", answer: "Yes — our Starter plan is free forever with no credit card required. It includes 3 projects and up to 5 team members." },
      { category: "Billing", question: "Can I cancel any time?", answer: "Absolutely. There are no long-term contracts and you can cancel your subscription instantly from your dashboard." },
      { category: "Security", question: "Is my data encrypted?", answer: "All data is encrypted at rest (AES-256) and in transit (TLS 1.3). We hold SOC 2 Type II certification." },
      { category: "Security", question: "Where is my data stored?", answer: "Data is stored in AWS us-east-1 by default, with optional EU residency on Growth and Enterprise plans." },
      { category: "Product", question: "Does Atlas integrate with GitHub?", answer: "Yes — our GitHub integration auto-closes issues on merge, links PRs to tasks, and syncs status in real time." },
      { category: "Product", question: "Is there a mobile app?", answer: "iOS and Android apps are available in the App Store and Google Play. Full feature parity with the desktop experience." },
    ],
    contactCtaLabel: "Talk to a human",
    contactCtaHref: "#contact",
  },
  'slick-cta-glass': {
    eyebrow: "★ READY WHEN YOU ARE",
    heading: "Stop juggling tools.",
    headingAccent: "Start shipping.",
    subtext: "Join 12,000+ teams who replaced their messy stack with Atlas. Free for 14 days, no card required.",
    primaryCtaLabel: "Start free trial",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Talk to sales",
    secondaryCtaHref: "#sales",
  },
  'slick-team': {
    eyebrow: "★ OUR TEAM",
    heading: "Small team,",
    headingAccent: "big ambitions.",
    subheading: "A globally distributed team of designers, engineers, and product thinkers.",
    members: [
      { name: "Alex Morgan", role: "CEO & Co-founder", bio: "Previously VP Product at Stripe. Building the tools I always wished existed.", avatarUrl: "https://i.pravatar.cc/300?img=11", linkedinUrl: "#", accent: "lime" },
      { name: "Jamie Liu", role: "CTO & Co-founder", bio: "ex-Google SRE. Obsessed with reliability, performance, and clean APIs.", avatarUrl: "https://i.pravatar.cc/300?img=12", linkedinUrl: "#", accent: "violet" },
      { name: "Sam Okafor", role: "Head of Design", bio: "Figma power user. Believes every pixel should earn its place.", avatarUrl: "https://i.pravatar.cc/300?img=13", linkedinUrl: "#", accent: "amber" },
      { name: "Taylor Reed", role: "Head of Growth", bio: "Turned Notion into a 7-figure business. Now doing it again.", avatarUrl: "https://i.pravatar.cc/300?img=14", linkedinUrl: "#", accent: "pink" },
    ],
  },
  'slick-integrations': {
    eyebrow: "★ INTEGRATIONS",
    heading: "Plays well with",
    headingAccent: "everything.",
    subheading: "Native integrations with 100+ tools — and a robust API for anything we haven't built yet.",
    logos: [
      { name: "Slack", src: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Slack_icon_2019.svg" },
      { name: "GitHub", src: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" },
      { name: "Figma", src: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
      { name: "Linear", src: "https://linear.app/favicon.ico" },
      { name: "Notion", src: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png" },
      { name: "Zapier", src: "https://cdn.zapier.com/zcms/assets/images/favicon-128.png" },
      { name: "Sentry", src: "https://sentry-brand.storage.googleapis.com/sentry-glyph-black.png" },
      { name: "Vercel", src: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico" },
    ],
    ctaLabel: "Browse all integrations",
    ctaHref: "#integrations",
  },
  'slick-blog-grid': {
    eyebrow: "★ FROM THE BLOG",
    heading: "Notes, news,",
    headingAccent: "& deep dives.",
    subheading: "Writing from our team on engineering, product, and the craft of building software.",
    posts: [
      { coverUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80", tag: "Engineering", title: "How we reduced p99 latency by 80% with edge caching", excerpt: "A deep dive into our infrastructure evolution, the mistakes we made, and the architecture that finally worked.", authorName: "Jamie Liu", authorAvatarUrl: "https://i.pravatar.cc/40?img=12", date: "May 12, 2025", readTime: "8 min read", href: "#" },
      { coverUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80", tag: "Product", title: "Why we killed our settings page — and what we replaced it with", excerpt: "Settings pages are where UX goes to die. Here's how we rethought configuration as a first-class feature.", authorName: "Sam Okafor", authorAvatarUrl: "https://i.pravatar.cc/40?img=13", date: "Apr 28, 2025", readTime: "5 min read", href: "#" },
      { coverUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80", tag: "Culture", title: "Building a fully async team across 9 time zones", excerpt: "What we've learned, what we'd do differently, and the processes that actually stuck when everyone is remote.", authorName: "Taylor Reed", authorAvatarUrl: "https://i.pravatar.cc/40?img=14", date: "Apr 10, 2025", readTime: "6 min read", href: "#" },
    ],
    ctaLabel: "Read all posts",
    ctaHref: "#blog",
  },
  'slick-timeline': {
    eyebrow: "★ HOW IT WORKS",
    heading: "From signup to shipping",
    headingAccent: "in under an hour.",
    subheading: "A guided onboarding that gets your team productive on day one.",
    steps: [
      { icon: "🏠", title: "Create your workspace", description: "Sign up in 30 seconds. Invite your team. Your workspace is pre-configured with sensible defaults." },
      { icon: "🔗", title: "Connect your tools", description: "Link GitHub, Slack, Figma, and 80+ other apps with a single click. No API keys needed." },
      { icon: "📋", title: "Plan your first sprint", description: "Import your backlog or start fresh. Drag tasks into sprints, set due dates, assign owners." },
      { icon: "🚀", title: "Ship and celebrate", description: "Close issues, merge PRs, and watch your burndown chart reach zero. Then do it again." },
    ],
  },
  'slick-app-download': {
    eyebrow: 'GET THE APP',
    heading: 'Download',
    headingAccent: 'DigiVyapar',
    subtext: 'Available on Android and iOS. Scan the QR code or tap to install.',
    stores: [
      { badgeImage: '', storeUrl: '#', deviceLabel: 'Android phones & tablets', qrImage: '', qrLabel: 'Scan to install' },
      { badgeImage: '', storeUrl: '#', deviceLabel: 'iPhone & iPad', qrImage: '', qrLabel: 'Scan to install' },
    ],
  },
  'slick-app-showcase': {
    eyebrow: 'THE PLATFORM',
    heading: 'One app for',
    headingAccent: 'all your favourite brands',
    tagline: 'All Your Favourite Brands, One Place  ·  Buy from authorised distributors  ·  Remote & WhatsApp orders',
    speed: 35,
    cardWidth: 260,
    cardHeight: 520,
    cards: [
      { title: 'Discover New Products', subtitle: 'Explore new products your customers may love.', image: '', cardBg: '#0A3028' },
      { title: 'Smart Catalog & Quick Ordering', subtitle: 'Search, filter, and order products in seconds.', image: '', cardBg: '#0A3028' },
      { title: 'Brand Wise Organized Checkout', subtitle: 'Review your order in one clear view.', image: '', cardBg: '#0A3028' },
      { title: 'All Your Favourite Brands, One Place', subtitle: 'Discover offers/products effortlessly.', image: '', cardBg: '#0A3028' },
      { title: 'Shop by Brands', subtitle: 'Quick access to all the brands you stock.', image: '', cardBg: '#0A3028' },
    ],
  },
  'slick-promo-banner': {
    heading: 'Special Offer',
    headingColor: '#FFD700',
    subheading: 'Limited time only',
    steps: ['Download the app today', 'Place your first order', 'Get ₹200 FREE'],
    ctaLabel: 'Download Now',
    ctaHref: '#',
    image: '',
    bgColor: '#00B39F',
  },
  'slick-footer-complex': {
    brandName: "Atlas",
    tagline: "The workspace where modern product teams plan, build, and ship together.",
    columns: [
      { title: "Product", links: [{ label: "Features", href: "#" }, { label: "Pricing", href: "#" }, { label: "Changelog", href: "#" }, { label: "Roadmap", href: "#" }] },
      { title: "Company", links: [{ label: "About", href: "#" }, { label: "Blog", href: "#" }, { label: "Careers", href: "#" }, { label: "Press", href: "#" }] },
      { title: "Resources", links: [{ label: "Docs", href: "#" }, { label: "API", href: "#" }, { label: "Status", href: "#" }, { label: "Security", href: "#" }] },
    ],
    socials: [
      { name: "twitter", href: "#" },
      { name: "github", href: "#" },
      { name: "linkedin", href: "#" },
    ],
    newsletterHeading: "Get the monthly dispatch",
    newsletterSubtext: "Product updates and engineering deep-dives, once a month. No spam.",
    newsletterPlaceholder: "you@company.com",
    newsletterCtaLabel: "Subscribe →",
    copyright: "© 2025 Atlas Labs, Inc. All rights reserved.",
    giantBrandWord: "Atlas",
  },
};
