import type { BlockType } from "./types";

export type ButtonField = { label: string; url: string; variant: "primary" | "secondary" | "outline" | "ghost"; color?: string; textColor?: string };
export type LinkField = { label: string; url: string };

export const DEFAULT_FIELDS: Record<Exclude<BlockType, "layout">, Record<string, unknown>> = {
  "nav-simple": {
    logoImage: "",
    logoText: "Acme",
    cta: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
    ctaSecondary: { label: "Log in", url: "#", variant: "ghost" } as ButtonField,
    links: [
      { label: "Home", url: "#" },
      { label: "About", url: "#" },
      { label: "Pricing", url: "#" },
    ] as LinkField[],
  },
  "nav-centered": {
    logoImage: "",
    logoText: "Acme",
    links: [
      { label: "Home", url: "#" },
      { label: "Features", url: "#" },
      { label: "Pricing", url: "#" },
      { label: "Contact", url: "#" },
    ] as LinkField[],
  },
  "footer-simple": {
    logoImage: "",
    logoText: "Acme",
    copyright: "© 2025 Acme Inc.",
    links: [
      { label: "Privacy", url: "#" },
      { label: "Terms", url: "#" },
      { label: "Contact", url: "#" },
    ] as LinkField[],
  },
  "footer-columns": {
    logoImage: "",
    logoText: "Acme",
    tagline: "Build better websites.",
    copyright: "© 2025 Acme Inc.",
    col1Title: "Product",
    col1Links: [
      { label: "Features", url: "#" },
      { label: "Pricing", url: "#" },
      { label: "Docs", url: "#" },
    ] as LinkField[],
    col2Title: "Company",
    col2Links: [
      { label: "About", url: "#" },
      { label: "Blog", url: "#" },
      { label: "Careers", url: "#" },
    ] as LinkField[],
    col3Title: "Legal",
    col3Links: [
      { label: "Privacy", url: "#" },
      { label: "Terms", url: "#" },
      { label: "Cookies", url: "#" },
    ] as LinkField[],
  },
  "hero-centered": {
    headline: "Build beautiful websites",
    subtext: "No code required. Launch in minutes.",
    primaryCta: { label: "Start free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "See demo", url: "#", variant: "outline" } as ButtonField,
    bgImage: "",
  },
  "hero-split": {
    headline: "Launch faster than ever",
    subtext: "Ship production-ready pages without writing code.",
    cta: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
    image: "",
    imageRight: true,
  },
  "features-3col": {
    title: "Why choose us",
    subtext: "Everything you need to build and grow.",
    features: [
      { icon: "⚡", title: "Lightning fast", description: "Build pages in seconds." },
      { icon: "🎨", title: "Beautiful design", description: "Stunning templates included." },
      { icon: "🔧", title: "Customizable", description: "Tweak every pixel." },
    ],
  },
  "features-4col": {
    title: "Everything you need",
    subtext: "Powerful features to ship faster.",
    features: [
      { icon: "⚡", title: "Fast", description: "Lightning quick performance." },
      { icon: "🎨", title: "Beautiful", description: "Designed with care." },
      { icon: "🔧", title: "Flexible", description: "Customize anything." },
      { icon: "🚀", title: "Scalable", description: "Grows with your team." },
    ],
  },
  "text-image": {
    headline: "A better way to build",
    subtext: "Pair powerful tools with a beautiful interface that scales with your team.",
    image: "",
    imageRight: true,
  },
  "stats-bar": {
    stats: [
      { number: "10,000", label: "Users", prefix: "", suffix: "+" },
      { number: "99.9", label: "Uptime", prefix: "", suffix: "%" },
      { number: "50", label: "Countries", prefix: "", suffix: "+" },
      { number: "24/7", label: "Support", prefix: "", suffix: "" },
    ],
  },
  testimonials: {
    items: [
      { quote: "This product changed how our team ships.", author: "Jane Doe", role: "CEO, Company", avatar: "" },
      { quote: "Best decision we made this year.", author: "John Smith", role: "CTO, Startup", avatar: "" },
      { quote: "I can't imagine working without it.", author: "Alex Lee", role: "PM, Agency", avatar: "" },
    ],
  },
  "logo-grid": {
    title: "Trusted by leading teams",
    logos: Array.from({ length: 6 }).map((_, i) => ({ src: "", alt: `Logo ${i + 1}` })),
  },
  "cta-banner": {
    headline: "Ready to get started?",
    subtext: "Join thousands of teams already building with PageBuilder.",
    button: { label: "Get started", url: "#", variant: "primary" } as ButtonField,
  },
  faq: {
    title: "Frequently asked questions",
    items: [
      { question: "How does it work?", answer: "Sign up and start building in minutes." },
      { question: "Is there a free plan?", answer: "Yes, our free plan includes core features." },
      { question: "Can I cancel anytime?", answer: "Absolutely — no contracts." },
      { question: "Do you offer support?", answer: "24/7 support on all paid plans." },
    ],
  },
  "blog-preview": {
    title: "From our blog",
    subtitle: "Thoughts, ideas, and insights from our team.",
    count: 3,
    ctaLabel: "View all posts",
    ctaUrl: "/blog",
  },
  "hero-gradient": {
    badge: "✦ New — AI-powered platform",
    headline: "Build faster with\nless friction",
    subtext: "The modern platform that helps teams ship products 2× faster. Loved by 10,000+ companies.",
    primaryCta: { label: "Start free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "See demo", url: "#", variant: "ghost" } as ButtonField,
    image: "",
  },
  "hero-centered-image": {
    badge: "Trusted by 10,000+ teams",
    headline: "The website builder\nyour team will love",
    subtext: "Design beautiful pages without writing code. Publish in minutes.",
    primaryCta: { label: "Get started free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "View demo", url: "#", variant: "outline" } as ButtonField,
    image: "https://placehold.co/1200x600/f1f5f9/94a3b8?text=Product+Screenshot",
  },
  "features-alternating": {
    title: "Everything you need to grow",
    subtext: "Powerful features built for modern teams",
    items: [
      { tag: "Design", title: "Drag-and-drop page builder", description: "Create stunning pages visually. No design skills needed. Hundreds of ready-made blocks.", image: "https://placehold.co/600x400/eff6ff/3b82f6?text=Feature+1", ctaLabel: "Learn more", ctaUrl: "#" },
      { tag: "Performance", title: "Blazing fast by default", description: "Every page is automatically optimised for Core Web Vitals. Your visitors get instant load times.", image: "https://placehold.co/600x400/f0fdf4/22c55e?text=Feature+2", ctaLabel: "Learn more", ctaUrl: "#" },
      { tag: "Analytics", title: "Built-in analytics dashboard", description: "See who visits your site, where they come from, and what they do. No third-party tools needed.", image: "https://placehold.co/600x400/fdf4ff/a855f7?text=Feature+3", ctaLabel: "Learn more", ctaUrl: "#" },
    ],
  },
  "features-icon-cards": {
    title: "Why teams choose us",
    subtext: "Built for speed, designed for scale",
    columns: 3,
    features: [
      { icon: "⚡", iconBg: "#eff6ff", title: "Lightning fast", description: "Pages load in under 200ms with our global CDN." },
      { icon: "🎨", iconBg: "#fdf4ff", title: "Beautiful templates", description: "50+ professionally designed templates to start from." },
      { icon: "🔒", iconBg: "#f0fdf4", title: "Enterprise security", description: "SOC2 compliant with 99.9% uptime SLA." },
      { icon: "📊", iconBg: "#fff7ed", title: "Smart analytics", description: "Understand your audience with built-in insights." },
      { icon: "🤝", iconBg: "#fef2f2", title: "Team collaboration", description: "Work together in real-time with live cursors." },
      { icon: "🔌", iconBg: "#f8fafc", title: "Integrations", description: "Connect with 100+ tools you already use." },
    ],
  },
  "pricing-modern": {
    title: "Simple, transparent pricing",
    subtext: "No hidden fees. Cancel anytime.",
    plans: [
      { name: "Starter", price: "$0", period: "/month", description: "Perfect for personal projects", highlighted: false, features: ["5 pages", "Custom domain", "Basic analytics", "Community support"], cta: { label: "Get started", url: "#", variant: "outline" } },
      { name: "Pro", price: "$29", period: "/month", description: "For growing businesses", highlighted: true, features: ["Unlimited pages", "Custom domain", "Advanced analytics", "Priority support", "Remove branding", "A/B testing"], cta: { label: "Start free trial", url: "#", variant: "primary" } },
      { name: "Enterprise", price: "$99", period: "/month", description: "For large teams", highlighted: false, features: ["Everything in Pro", "SSO / SAML", "Dedicated support", "Custom contracts", "SLA guarantee", "On-premise option"], cta: { label: "Contact sales", url: "#", variant: "outline" } },
    ],
  },
  "testimonials-wall": {
    title: "Loved by thousands of teams",
    items: [
      { quote: "This builder saved us months of development time. Our marketing team now ships landing pages independently.", author: "Sarah Chen", role: "Head of Marketing", company: "Acme Corp", stars: 5 },
      { quote: "The templates are absolutely beautiful. We went from zero to live website in one afternoon.", author: "Marcus Williams", role: "Founder", company: "BuildFast", stars: 5 },
      { quote: "Finally a no-code tool that doesn't feel like a compromise. Our dev team actually approves.", author: "Priya Patel", role: "CTO", company: "ScaleUp", stars: 5 },
      { quote: "We cut our web production costs by 60%. The ROI was immediate.", author: "James Liu", role: "VP Product", company: "GrowthCo", stars: 5 },
      { quote: "Best page builder I've used in 10 years. The AI suggestions are a game changer.", author: "Elena Rodriguez", role: "Designer", company: "Studio R", stars: 5 },
      { quote: "Our conversion rate went up 34% after rebuilding our landing page with this tool.", author: "Tom Bergmann", role: "Growth Lead", company: "Fintech Inc", stars: 5 },
    ],
  },
  "team-grid": {
    title: "Meet the team",
    subtext: "The people building the future of web design",
    members: [
      { name: "Alex Johnson", role: "CEO & Co-founder", avatar: "https://placehold.co/300x300/e0e7ff/4f46e5?text=AJ", linkedin: "#" },
      { name: "Maria Garcia", role: "Head of Design", avatar: "https://placehold.co/300x300/fce7f3/db2777?text=MG", linkedin: "#" },
      { name: "David Kim", role: "Lead Engineer", avatar: "https://placehold.co/300x300/d1fae5/059669?text=DK", linkedin: "#" },
      { name: "Sarah Brown", role: "Head of Product", avatar: "https://placehold.co/300x300/fef3c7/d97706?text=SB", linkedin: "#" },
    ],
  },
  "stats-bold": {
    title: "Trusted by teams worldwide",
    stats: [
      { number: "50K", suffix: "+", label: "Active users" },
      { number: "99.9", suffix: "%", label: "Uptime SLA" },
      { number: "2×", suffix: "", label: "Faster launches" },
      { number: "4.9", suffix: "★", label: "Average rating" },
    ],
  },
  "steps-process": {
    title: "Get started in minutes",
    subtext: "No credit card required",
    steps: [
      { number: "01", title: "Create your account", description: "Sign up free in 30 seconds. No credit card needed." },
      { number: "02", title: "Choose a template", description: "Pick from 50+ professionally designed templates." },
      { number: "03", title: "Customise & publish", description: "Edit content, add your brand, and go live instantly." },
    ],
  },
  "cta-banner-gradient": {
    headline: "Ready to build something amazing?",
    subtext: "Join 50,000+ teams already using our platform. Free forever for small teams.",
    primaryCta: { label: "Start for free", url: "#", variant: "primary" } as ButtonField,
    secondaryCta: { label: "Talk to sales", url: "#", variant: "ghost" } as ButtonField,
  },
  "hero-salescode": {
    badge: "World's First AI Native Platform for CPG Sales",
    title: "All your CPG Sales on One Platform.",
    description: "Build your SFA, DMS, eB2B and AI agents...",
    ctaText: "Build Your Stack",
    ctaUrl: "#product-selection",
  },
  "impact-salescode": {
    title: "Business Impact Guaranteed\nwith AI for SFA and eB2B for CPG Sales",
    videoUrl: "https://salescode.ai/wp-content/uploads/2025/09/flow-animaiton-solution-to-deployment3.mp4",
    stats: [
      { value: "35", suffix: "%", description: "Reduction in Cost-to-Serve" },
      { value: "18", suffix: "%", description: "Increase in Distribution" },
      { value: "5", suffix: "%", description: "Reduction in Daily Sales Loss" },
      { value: "3", suffix: "x", description: "Minimum Sales Uplift" },
    ],
  },
  "clients-salescode": {
    title: "Privileged to work with Top CPG Brands",
    sectionId: "cpg-brands",
  },
  "security-salescode": {
    heading: "Your Data is Safe with Us",
    certs: [
      { url: "https://salescode.ai/wp-content/uploads/2025/09/GDPR-1-r23yrj45d5eecfx8318k9wj5vikzl0sfdvoueb8d4w.webp", alt: "GDPR" },
      { url: "https://salescode.ai/wp-content/uploads/2025/09/ISO-1-r23yqigfym07rneh13e42ns6phlo8tqw8u8woiqpvk.webp", alt: "ISO 27001" },
      { url: "https://salescode.ai/wp-content/uploads/2025/09/SOC-1-r23ytr0fi2frrap64hrunudcd9n6ralm0v546txwg0.webp", alt: "SOC 2 Type 2" },
    ],
  },
  "experience-video-salescode": {
    videoUrl: "https://salescode.ai/wp-content/uploads/2025/09/experience-center-vid-for-website-video2.mp4",
    title: "SalesCode Experience Center",
    subtitle: "Experience the 'Code of Future-Ready Sales Teams & Trade'",
    linkText: "",
    linkUrl: "",
  },
  "cta-salescode": {
    badge: "Ready to Deploy",
    heading: "Ready to build your AI-powered sales platform?",
    subtext: "Start with SFA, DMS, or eB2B — or combine all three with SCAI. Go live in weeks with guaranteed, contractual results.",
    ctaText: "Build Your Stack →",
    ctaUrl: "#product-selection",
  },
  "navbar-salescode-slot": {
    bgColor: "",
    links: [
      { label: "About Us",   href: "/about" },
      { label: "Clients",    href: "/clients" },
      { label: "Blogs",      href: "/blog" },
      { label: "Contact Us", href: "/contact-us" },
    ],
  },
  "product-selection-slot": {},
  "platform-features-slot": {},
  "integrations-slot": {},
  "blogs-section-slot": {},
  "footer-salescode-slot": {},
  "about-page-slot": {},
  "clients-page-slot": {},
  "contact-page-slot": {},
  "blog-page-slot": {},
  'slick-hero-split': {
    badge: "New · Spring release",
    headlineStart: "Run your whole business on",
    headlineAccent: "one platform",
    headlineEnd: "your team will actually love.",
    subtitle: "From CRM to invoicing, inventory to email campaigns — replace twelve tools with one beautifully integrated suite.",
    primaryCtaLabel: "Start free — no card",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Watch 2-min demo",
    secondaryCtaHref: "#demo",
    mockupImageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80",
    trustLabel: "Trusted by 7M+ users worldwide",
  },
  'slick-hero-video': {
    eyebrow: "★ FEATURED IN TECHCRUNCH",
    headlineTop: "The operating system",
    headlineAccent: "for modern",
    headlineBottom: "businesses.",
    subtitle: "Beautifully designed apps that work together out of the box. Built for teams that ship.",
    primaryCtaLabel: "Get started — it's free",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Talk to sales",
    secondaryCtaHref: "#sales",
    videoPoster: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&q=80",
    videoSrc: "",
    metrics: [
      { value: "4.9/5", label: "G2 rating" },
      { value: "12k+", label: "Active teams" },
      { value: "99.99%", label: "Uptime" },
    ],
  },
  'slick-features-bento': {
    eyebrow: "★ FEATURES",
    heading: "Everything you need.",
    headingAccent: "Nothing you don't.",
    subheading: "A focused toolkit that scales from your first hire to your first IPO.",
    features: [
      { icon: "⚡", title: "Realtime sync", description: "Every change reflected in under 200 ms across all devices.", tone: "lime", span: "md" },
      { icon: "🔒", title: "SOC 2 Type II", description: "Enterprise security built in, not bolted on.", tone: "violet", span: "sm" },
      { icon: "🤖", title: "AI inbox", description: "Triage, draft replies, and close tickets in seconds.", tone: "amber", span: "lg" },
      { icon: "📊", title: "Live dashboards", description: "Drag-and-drop analytics that update in real time.", tone: "pink", span: "sm" },
      { icon: "🌍", title: "Global edge", description: "Deployed to 200+ PoPs for sub-10 ms response anywhere.", tone: "sky", span: "md" },
      { icon: "🔌", title: "100+ integrations", description: "Connect your existing stack in one click.", tone: "ink", span: "md" },
    ],
  },
  'slick-features-alternating': {
    rows: [
      { tag: "PLANNING", headline: "Plan your", headlineAccent: "entire roadmap", description: "From epics to sub-tasks, structure your work exactly the way your team thinks.", bullets: ["Nested tasks with dependencies", "Custom fields and workflows", "Milestone tracking"], ctaLabel: "See planning features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80", accent: "lime" },
      { tag: "BUILDING", headline: "Ship code", headlineAccent: "with confidence", description: "Git-native project tracking that keeps engineers in flow and managers informed.", bullets: ["Branch-to-issue linking", "Auto-close on merge", "PR review queues"], ctaLabel: "See dev features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80", accent: "violet" },
      { tag: "SHIPPING", headline: "Release with", headlineAccent: "zero drama", description: "One-click deployments, staged rollouts, and instant rollback — all from your dashboard.", bullets: ["Feature flags built-in", "Canary releases", "One-click rollback"], ctaLabel: "See shipping features →", ctaHref: "#", imageUrl: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80", accent: "amber" },
    ],
  },
  'slick-pricing': {
    eyebrow: "★ PRICING",
    heading: "One price.",
    headingAccent: "Everything included.",
    subheading: "No seat fees. No hidden add-ons. Cancel any time.",
    currency: "$",
    plans: [
      { name: "Starter", description: "Perfect for solo makers and early-stage startups.", monthlyPrice: 0, annualPrice: 0, features: ["Up to 3 projects", "5 team members", "1 GB storage", "Community support"], ctaLabel: "Get started free", ctaHref: "#start", highlighted: false },
      { name: "Growth", description: "Built for teams moving fast and shipping often.", monthlyPrice: 29, annualPrice: 24, features: ["Unlimited projects", "25 team members", "50 GB storage", "Priority support", "Advanced analytics", "Custom domains"], ctaLabel: "Start 14-day trial", ctaHref: "#trial", highlighted: true, badge: "Most popular" },
      { name: "Enterprise", description: "For organizations that need security and scale.", monthlyPrice: 99, annualPrice: 79, features: ["Everything in Growth", "Unlimited members", "SSO & SAML", "Audit logs", "99.99% SLA", "Dedicated success manager"], ctaLabel: "Talk to sales", ctaHref: "#sales", highlighted: false },
    ],
  },
  'slick-testimonials-carousel': {
    eyebrow: "★ LOVED BY TEAMS",
    heading: "Twelve thousand teams",
    headingAccent: "can't be wrong.",
    testimonials: [
      { quote: "Switching to Atlas was the best decision we made all year. Our sprint velocity doubled in the first month.", rating: 5, name: "Sarah Chen", role: "VP Engineering", company: "Stripe", avatarUrl: "https://i.pravatar.cc/120?img=1" },
      { quote: "We replaced Jira, Confluence, and Notion with Atlas. Same features, one tenth the complexity.", rating: 5, name: "Marcus Hill", role: "CTO", company: "Vercel", avatarUrl: "https://i.pravatar.cc/120?img=2" },
      { quote: "The AI triage alone saves my support team 4 hours every day. I'd never go back.", rating: 5, name: "Priya Nair", role: "Head of Customer Success", company: "Linear", avatarUrl: "https://i.pravatar.cc/120?img=3" },
      { quote: "Onboarding took 20 minutes. That's unheard of for enterprise software.", rating: 5, name: "Tom Briggs", role: "Director of Ops", company: "Shopify", avatarUrl: "https://i.pravatar.cc/120?img=4" },
    ],
  },
  'slick-testimonials-logos': {
    eyebrow: "★ TRUSTED AT EVERY STAGE",
    heading: "From seed to",
    headingAccent: "S&P 500.",
    logos: [
      { name: "Stripe", src: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg" },
      { name: "Notion", src: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png" },
      { name: "Figma", src: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
      { name: "Vercel", src: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico" },
      { name: "Shopify", src: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Shopify_logo_2018.svg" },
      { name: "Loom", src: "https://i.pravatar.cc/40?img=10" },
    ],
    quote: "Atlas is the rare tool that made our team faster without adding process. It just gets out of the way.",
    authorName: "Elena Park",
    authorRole: "Director of Engineering",
    authorCompany: "Loom",
    authorAvatarUrl: "https://i.pravatar.cc/120?img=49",
  },
  'slick-stats': {
    eyebrow: "★ BY THE NUMBERS",
    heading: "Built for scale.",
    headingAccent: "Trusted at scale.",
    description: "Five years obsessing over performance and developer experience — and the numbers show it.",
    stats: [
      { value: "12,400", suffix: "+", label: "Teams worldwide" },
      { value: "99.99", suffix: "%", label: "Uptime guaranteed" },
      { value: "3.2", suffix: "x", label: "Faster cycle time" },
      { value: "48", suffix: "M", label: "Issues shipped" },
    ],
  },
  'slick-faq': {
    eyebrow: "★ FAQ",
    heading: "Questions,",
    headingAccent: "answered.",
    subheading: "Can't find what you're looking for? Reach out — we usually reply within an hour.",
    items: [
      { category: "Billing", question: "Is there a free plan?", answer: "Yes — our Starter plan is free forever with no credit card required. It includes 3 projects and up to 5 team members." },
      { category: "Billing", question: "Can I cancel any time?", answer: "Absolutely. There are no long-term contracts and you can cancel your subscription instantly from your dashboard." },
      { category: "Security", question: "Is my data encrypted?", answer: "All data is encrypted at rest (AES-256) and in transit (TLS 1.3). We hold SOC 2 Type II certification." },
      { category: "Security", question: "Where is my data stored?", answer: "Data is stored in AWS us-east-1 by default, with optional EU residency on Growth and Enterprise plans." },
      { category: "Product", question: "Does Atlas integrate with GitHub?", answer: "Yes — our GitHub integration auto-closes issues on merge, links PRs to tasks, and syncs status in real time." },
      { category: "Product", question: "Is there a mobile app?", answer: "iOS and Android apps are available in the App Store and Google Play. Full feature parity with the desktop experience." },
    ],
    contactCtaLabel: "Talk to a human",
    contactCtaHref: "#contact",
  },
  'slick-cta-glass': {
    eyebrow: "★ READY WHEN YOU ARE",
    heading: "Stop juggling tools.",
    headingAccent: "Start shipping.",
    subtext: "Join 12,000+ teams who replaced their messy stack with Atlas. Free for 14 days, no card required.",
    primaryCtaLabel: "Start free trial",
    primaryCtaHref: "#start",
    secondaryCtaLabel: "Talk to sales",
    secondaryCtaHref: "#sales",
  },
  'slick-team': {
    eyebrow: "★ OUR TEAM",
    heading: "Small team,",
    headingAccent: "big ambitions.",
    subheading: "A globally distributed team of designers, engineers, and product thinkers.",
    members: [
      { name: "Alex Morgan", role: "CEO & Co-founder", bio: "Previously VP Product at Stripe. Building the tools I always wished existed.", avatarUrl: "https://i.pravatar.cc/300?img=11", linkedinUrl: "#", accent: "lime" },
      { name: "Jamie Liu", role: "CTO & Co-founder", bio: "ex-Google SRE. Obsessed with reliability, performance, and clean APIs.", avatarUrl: "https://i.pravatar.cc/300?img=12", linkedinUrl: "#", accent: "violet" },
      { name: "Sam Okafor", role: "Head of Design", bio: "Figma power user. Believes every pixel should earn its place.", avatarUrl: "https://i.pravatar.cc/300?img=13", linkedinUrl: "#", accent: "amber" },
      { name: "Taylor Reed", role: "Head of Growth", bio: "Turned Notion into a 7-figure business. Now doing it again.", avatarUrl: "https://i.pravatar.cc/300?img=14", linkedinUrl: "#", accent: "pink" },
    ],
  },
  'slick-integrations': {
    eyebrow: "★ INTEGRATIONS",
    heading: "Plays well with",
    headingAccent: "everything.",
    subheading: "Native integrations with 100+ tools — and a robust API for anything we haven't built yet.",
    logos: [
      { name: "Slack", src: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Slack_icon_2019.svg" },
      { name: "GitHub", src: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" },
      { name: "Figma", src: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
      { name: "Linear", src: "https://linear.app/favicon.ico" },
      { name: "Notion", src: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png" },
      { name: "Zapier", src: "https://cdn.zapier.com/zcms/assets/images/favicon-128.png" },
      { name: "Sentry", src: "https://sentry-brand.storage.googleapis.com/sentry-glyph-black.png" },
      { name: "Vercel", src: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico" },
    ],
    ctaLabel: "Browse all integrations",
    ctaHref: "#integrations",
  },
  'slick-blog-grid': {
    eyebrow: "★ FROM THE BLOG",
    heading: "Notes, news,",
    headingAccent: "& deep dives.",
    subheading: "Writing from our team on engineering, product, and the craft of building software.",
    posts: [
      { coverUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80", tag: "Engineering", title: "How we reduced p99 latency by 80% with edge caching", excerpt: "A deep dive into our infrastructure evolution, the mistakes we made, and the architecture that finally worked.", authorName: "Jamie Liu", authorAvatarUrl: "https://i.pravatar.cc/40?img=12", date: "May 12, 2025", readTime: "8 min read", href: "#" },
      { coverUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80", tag: "Product", title: "Why we killed our settings page — and what we replaced it with", excerpt: "Settings pages are where UX goes to die. Here's how we rethought configuration as a first-class feature.", authorName: "Sam Okafor", authorAvatarUrl: "https://i.pravatar.cc/40?img=13", date: "Apr 28, 2025", readTime: "5 min read", href: "#" },
      { coverUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80", tag: "Culture", title: "Building a fully async team across 9 time zones", excerpt: "What we've learned, what we'd do differently, and the processes that actually stuck when everyone is remote.", authorName: "Taylor Reed", authorAvatarUrl: "https://i.pravatar.cc/40?img=14", date: "Apr 10, 2025", readTime: "6 min read", href: "#" },
    ],
    ctaLabel: "Read all posts",
    ctaHref: "#blog",
  },
  'slick-timeline': {
    eyebrow: "★ HOW IT WORKS",
    heading: "From signup to shipping",
    headingAccent: "in under an hour.",
    subheading: "A guided onboarding that gets your team productive on day one.",
    steps: [
      { icon: "🏠", title: "Create your workspace", description: "Sign up in 30 seconds. Invite your team. Your workspace is pre-configured with sensible defaults." },
      { icon: "🔗", title: "Connect your tools", description: "Link GitHub, Slack, Figma, and 80+ other apps with a single click. No API keys needed." },
      { icon: "📋", title: "Plan your first sprint", description: "Import your backlog or start fresh. Drag tasks into sprints, set due dates, assign owners." },
      { icon: "🚀", title: "Ship and celebrate", description: "Close issues, merge PRs, and watch your burndown chart reach zero. Then do it again." },
    ],
  },
  'slick-app-download': {
    eyebrow: 'GET THE APP',
    heading: 'Download',
    headingAccent: 'DigiVyapar',
    subtext: 'Available on Android and iOS. Scan the QR code or tap to install.',
    stores: [
      { badgeImage: '', storeUrl: '#', deviceLabel: 'Android phones & tablets', qrImage: '', qrLabel: 'Scan to install' },
      { badgeImage: '', storeUrl: '#', deviceLabel: 'iPhone & iPad', qrImage: '', qrLabel: 'Scan to install' },
    ],
  },
  'slick-app-showcase': {
    eyebrow: 'THE PLATFORM',
    heading: 'One app for',
    headingAccent: 'all your favourite brands',
    tagline: 'All Your Favourite Brands, One Place  ·  Buy from authorised distributors  ·  Remote & WhatsApp orders',
    speed: 35,
    cardWidth: 260,
    cardHeight: 520,
    cards: [
      { title: 'Discover New Products', subtitle: 'Explore new products your customers may love.', image: '', cardBg: '#0A3028' },
      { title: 'Smart Catalog & Quick Ordering', subtitle: 'Search, filter, and order products in seconds.', image: '', cardBg: '#0A3028' },
      { title: 'Brand Wise Organized Checkout', subtitle: 'Review your order in one clear view.', image: '', cardBg: '#0A3028' },
      { title: 'All Your Favourite Brands, One Place', subtitle: 'Discover offers/products effortlessly.', image: '', cardBg: '#0A3028' },
      { title: 'Shop by Brands', subtitle: 'Quick access to all the brands you stock.', image: '', cardBg: '#0A3028' },
    ],
  },
  'slick-promo-banner': {
    heading: 'Special Offer',
    headingColor: '#FFD700',
    subheading: 'Limited time only',
    steps: ['Download the app today', 'Place your first order', 'Get ₹200 FREE'],
    ctaLabel: 'Download Now',
    ctaHref: '#',
    image: '',
    bgColor: '#00B39F',
  },
  'slick-dv-hero': {
    logo: '',
    headingPrefix: 'First',
    headingAccent: 'Cloud Distribution',
    headingLastLine: 'Platform',
    ctaPrimaryLabel: 'Register for DigiVyapar',
    ctaPrimaryHref: '#register',
    ctaSecondaryLabel: 'See how it works',
    demoVideoUrl: 'https://www.youtube.com/embed/3vFdNEJLk_A?autoplay=1',
    googlePlayUrl: 'https://play.google.com/store/apps/details?id=com.applicate.digivyapar.app&hl=en_IN',
    appStoreUrl: 'https://apps.apple.com/in/app/digivyapar/id6479580322',
    stat1Text: '25+ companies',
    stat2Text: '100K+ retailers in Phase 1',
    stat3Text: '1M+ digital stores vision',
    mockupImage: '',
  },
  'slick-dv-video-split': {
    eyebrow: 'ONDC: The Future of Distribution',
    heading: 'DigiVyapar for',
    headingAccent: 'every retailer',
    body: 'Access thousands of products from multiple brands on one platform. From product discovery and promotions to ordering and fulfilment, every step is streamlined through an ONDC-enabled distribution ecosystem designed for modern retail.',
    ctaLabel: 'Register for DigiVyapar',
    ctaHref: '#register',
    videoThumb: '',
    videoLabel: 'Watch: big news for kirana stores',
    videoUrl: 'https://www.youtube.com/embed/3vFdNEJLk_A?autoplay=1',
  },
  'slick-dv-vision': {
    eyebrow: 'DigiVyapar Vision',
    visionText: 'To create **1M+ digital stores**, empowered with **100% digital commerce**, for buying from their suppliers and serving their customers, to maximise **growth and profitability**.',
    stat1Value: '1M+',
    stat1Label: 'Digital stores vision',
    stat2Value: '25+',
    stat2Label: 'Companies onboard',
    stat3Value: '100K+',
    stat3Label: 'Retailers in Phase 1',
    stat4Value: '4',
    stat4Label: 'Markets at launch',
  },
  'slick-dv-carousel': {
    eyebrow: 'The Platform',
    heading: 'One app for',
    headingAccent: 'all your favourite brands',
    cap1: 'All Your Favourite Brands, One Place',
    cap2: 'Buy from authorised distributors',
    cap3: 'Remote & WhatsApp orders',
    cards: [
      { image: '', alt: 'All your favourite brands, one place' },
      { image: '', alt: 'Shop by brands' },
      { image: '', alt: 'Discover new products' },
      { image: '', alt: 'Smart catalog & quick ordering' },
      { image: '', alt: 'Brand wise organized checkout' },
    ],
  },
  'slick-dv-agent': {
    eyebrow: 'AI Sales Agent',
    heading: 'for distributors',
    headingAccent: 'AI Sales Agent',
    accentFirst: true,
    body: "Extend your sales team's reach with an AI agent that identifies reorder opportunities, nudges retailers, and engages stores when representatives are unavailable.",
    bullets: [
      'Automated Retailer Nudges',
      'Missed Order Recovery',
      'Sales Rep Absence Coverage',
    ],
    ctaLabel: 'Register for DigiVyapar',
    ctaHref: '#register',
    reversed: true,
    bgColor: '#111414',
    slides: [],
  },
  'slick-dv-split': {
    eyebrow: 'For Distributors',
    heading: 'Built on a',
    headingAccent: 'smarter distribution network',
    body: 'Empower your distribution business with a unified control center for orders, inventory, catalogues, payments, and retailer engagement.',
    bullets: [
      'Unified Order Management',
      'Real-Time Inventory Visibility',
      'Catalogue & Promotion Control',
      'Payment Reconciliation',
    ],
    ctaLabel: 'Register for DigiVyapar',
    ctaHref: '#register',
    reversed: false,
    slides: [],
  },
  'slick-dv-download': {
    eyebrow: 'Get the App',
    heading: 'Download',
    headingAccent: 'DigiVyapar',
    subtext: 'Available on Android and iOS. Scan the QR code or tap to install.',
    androidStoreUrl: 'https://play.google.com/store/apps/details?id=com.applicate.digivyapar.app&hl=en_IN',
    androidQrUrl: '',
    iosStoreUrl: 'https://apps.apple.com/in/app/digivyapar/id6479580322',
    iosQrUrl: '',
  },
  'slick-dv-who': {
    eyebrow: 'Built for the whole chain',
    heading: 'Who can onboard with',
    headingAccent: 'DigiVyapar',
    cards: [
      { icon: 'brands', title: 'Brands', description: 'Top, regional and D2C brands reaching retailers across the open network.' },
      { icon: 'distributors', title: 'Distributors', description: 'Authorised distributors fulfilling orders and expanding their coverage.' },
      { icon: 'retailers', title: 'Retailers', description: 'Kirana, chemist and convenience stores buying and selling digitally.' },
      { icon: 'apps', title: 'Company Apps', description: 'Existing company eB2B apps connected through cloud distribution APIs.' },
    ],
  },
  'slick-dv-register': {
    heading: 'Join DigiVyapar',
    rotatorWords: ['Retailers', 'Distributors', 'FMCG Brands'],
    body: 'Tell us a little about your business and we will help you get started on DigiVyapar.',
    bullets: ['Buy the best brands at the best rates', 'Remote and WhatsApp ordering', 'SLAs for delivery and service'],
    formTitle: 'ONDC Seller Registration',
    formSubtext: 'Join the network in a few simple steps',
    ctaLabel: 'Join ONDC',
    privacyUrl: '#',
    roles: ['Brand', 'Distributor', 'Retailer', 'Company App'],
    apiEndpoint: '/v1/digivyapar-registration',
    successTitle: "You're on the list",
    successMessage: "Thanks for your interest in DigiVyapar on ONDC. Our team will reach out shortly to get you started.",
  },
  'slick-sc-product-showcase': {
    eyebrowLabel: 'Explore Salescode.ai Products',
    headingPre: 'Experience Our AI Products',
    headingGradient: 'In Action',
    subtitle: 'Interactive product experiences that showcase how Salescode.ai transforms retail execution, sales productivity, and field force performance.',
    cards: [
      { title: 'IR Recognition',  ctaLabel: 'Explore Demo', ctaUrl: '#' },
      { title: 'AI Sales Agent',  ctaLabel: 'Explore Demo', ctaUrl: '#' },
      { title: 'AI Coach',        ctaLabel: 'Explore Demo', ctaUrl: '#' },
    ],
  },
  'slick-sc-ai-commerce': {
    eyebrowLabel: 'One AI commerce platform',
    headingPre: 'Future-Ready',
    headingGradient: 'AI Commerce Stack',
    subtitle: 'AI woven into every layer of sales, distribution, retail execution and distributor growth.',
    cards: [
      { kicker:'IR Recognition',  title:'Shelf Intelligence',        copy:'Detect every SKU, branded or unbranded, score compliance instantly and reward field reps in real time.',  ctaUrl:'#' },
      { kicker:'AI Native SFA',   title:'Smarter Sales Execution',   copy:'Generate targets, tasks, incentives and next-best actions for every outlet automatically.',               ctaUrl:'#' },
      { kicker:'AI Powered eB2B', title:'Intelligent Ordering',      copy:'Search, speak or type. AI builds personalized product baskets and predicts reorders.',                   ctaUrl:'#' },
      { kicker:'AI Native DMS',   title:'Distributor Automation',    copy:'Optimize inventory, working capital, route planning and service performance.',                           ctaUrl:'#' },
      { kicker:'AI Sales Agent',  title:'24×7 AI Sales Workforce',   copy:'Handles inbound calls, outbound selling, order taking and retailer engagement.',                        ctaUrl:'#' },
      { kicker:'AI Coach',        title:'Continuous Sales Coaching', copy:'Coach every rep daily with personalized guidance, mock calls and skill improvement plans.',              ctaUrl:'#' },
    ],
  },
  'slick-sc-integrations': {
    eyebrowLabel: 'Integrations',
    headingPre: '',
    headingGradient: 'Connect your entire stack',
    headingSuffix: '',
    subtitle: 'Choose from hundreds of ERP, DMS, CRM, payment and communication integrations that let Salescode.ai sync seamlessly with everything already running in your business.',
    ctaLabel: 'Book a Demo',
    ctaUrl: '#',
    tiles: [
      { imageUrl: '', alt: 'SMS'          }, // slot 0 — faded far-left
      { imageUrl: '', alt: 'WhatsApp'     }, // slot 1
      { imageUrl: '', alt: 'Azure'        }, // slot 2
      { imageUrl: '', alt: 'SAP'          }, // slot 3
      { imageUrl: '', alt: 'AWS'          }, // slot 4
      { imageUrl: '', alt: 'SharePoint'   }, // slot 5
      { imageUrl: '', alt: 'Google Cloud' }, // slot 6
      { imageUrl: '', alt: 'Paytm'        }, // slot 7
      { imageUrl: '', alt: 'Salesforce'   }, // slot 8
      { imageUrl: '', alt: 'Zoho'         }, // slot 9
      { imageUrl: '', alt: 'Tally'        }, // slot 10
      { imageUrl: '', alt: 'Oracle'       }, // slot 11
    ],
  },
  'slick-sc-blog-insights': {
    eyebrowLabel: 'Latest Insights',
    headingPre: 'Latest',
    headingGrad: 'Insights',
    headingSuffix: '& Stories',
    subtitle: 'Explore industry trends, AI innovation, sales transformation stories, customer success journeys, and retail intelligence insights.',
    featuredPost: {
      badge: 'AI Sales Agent',
      title: 'How AI Sales Agents Are Transforming FMCG Distribution Across India',
      ctaLabel: 'Read Article',
      ctaUrl: '#',
      imageUrl: '',
    },
    posts: [
      { badge: 'IR Recognition', title: 'The Future of Retail Shelf Intelligence with Computer Vision', ctaLabel: 'Read More', ctaUrl: '#', imageUrl: '' },
      { badge: 'AI Native SFA',  title: 'Why Next-Gen SFA Needs AI, Not More Dashboards',             ctaLabel: 'Read More', ctaUrl: '#', imageUrl: '' },
    ],
    viewAllLabel: 'View All Blogs',
    viewAllUrl: '#',
  },
  'slick-sfa-hero': {
    eyebrowLabel: 'AI Native SFA',
    headingPre: 'Make every rep sell like your ',
    headingGrad: 'top performer',
    headingSuffix: '',
    subtitle: 'AI generated tasks, targets and the perfect basket for every visit.',
    subtitleBold: 'A minimum 3% sales uplift, guaranteed,',
    ctaLabel: 'Request a Demo',
    ctaUrl: '#',
    ctaPlaceholder: 'Work email',
    trustText: 'Trusted by 22+ CPG companies · 18 countries · 65K+ reps',
  },
  'slick-sfa-ai-engine': {
    eyebrowLabel: 'Why SalesCode SFA',
    headingPre: 'One AI engine for every ',
    headingGrad: 'Task, Target and Incentive',
    headingSuffix: '',
    subtitle: 'Machine Learning decides what each rep should sell, where, and why, on every single visit.',
    tabs: [
      {
        label: 'AI Generated Tasks',
        tag: 'AI Task',
        heading: 'Prioritised tasks for every store, every visit',
        description: 'Machine Learning based, prioritised tasks for each store, for each visit, to achieve the KPI targets.',
        features: ['Incremental Order Target', 'Cross Sell Task', 'Recover Task'],
        impactValue: '5 to 8%',
        impactLabel: 'Sales uplift',
        impactSub: 'Prioritised tasks, per store, per visit',
      },
      {
        label: 'AI Generated Targets',
        tag: 'AI Target',
        heading: 'Hyper personalised targets for every call',
        description: 'Machine Learning based, most optimised and hyper personalised target for each store, for each call.',
        features: ['Hyper Personalised Target', 'Task Based Incentive', 'Must Order Stores', 'Premium Product Distribution'],
        impactValue: '3 to 5%',
        impactLabel: 'Sales uplift',
        impactSub: 'Optimised target, per store, per call',
      },
      {
        label: 'AI Generated Incentives',
        tag: 'AI Incentive',
        heading: 'Task based incentives, instant gratification',
        description: 'Task based incentives for each task, to drive action with instant gratification.',
        features: ['Live Incentive Tracker', 'Redemption Threshold', 'Incentive Points Spread', 'Multiple Redemption Options'],
        impactValue: '5 to 12%',
        impactLabel: 'Sales uplift',
        impactSub: 'Task based incentive, paid instantly',
      },
    ],
  },
  'slick-sfa-guarantee': {
    eyebrowLabel: 'The SalesCode Guarantee',
    headingPre: 'A minimum ',
    headingGrad: '3% sales uplift',
    headingSuffix: ', guaranteed.',
    subtitle: 'We put our results in the contract, not just the pitch deck. If the AI engine does not move your numbers, you do not carry the risk.',
    refundText: 'Or we refund 110% of your fee',
    ctaLabel: 'Get a Demo',
    ctaUrl: '#',
    proofLabel: 'Average sales uplift, proven in market',
    results: [
      { country: 'India',       value: '7%',    label: 'avg sales uplift' },
      { country: 'Mexico',      value: '12.6%', label: 'avg sales uplift' },
      { country: 'Philippines', value: '14.5%', label: 'avg sales uplift' },
    ],
    scopeItems: [
      'Demonstrated with 65+ brands',
      '18+ countries',
      '65k+ reps across 22+ CPG companies',
    ],
  },
  'slick-sfa-insights': {
    eyebrowLabel: 'CPG Industry Insights',
    headingPre: 'Where ',
    headingGrad: 'AI and traditional trade',
    headingSuffix: ' converge',
    lead: 'The biggest names in CPG are already turning AI into store level execution. SalesCode is how you do the same.',
    cards: [
      { logoText: 'Mondelez', logoSub: 'INTERNATIONAL', logoColor: '#4B2A87', logoItalic: false, imageUrl: '', title: 'Disrupting old technologies', detail: 'We brought in AI and looked at each store\'s historical buying data, and what nearby stores buy, to disrupt the old ways and drive our people forward.', brand: 'Mondelez International' },
      { logoText: 'AB InBev', logoSub: '', logoColor: '#16191E', logoItalic: false, imageUrl: '', title: '10x more effective sales visits', detail: 'A proprietary tasking algorithm identifies and prioritises the right tasks for each specific visit, increasing the effectiveness of every visit ten-fold.', brand: 'ABInBev' },
      { logoText: 'Coca-Cola', logoSub: 'HBC', logoColor: '#E0231B', logoItalic: true, imageUrl: '', title: 'Outlet level predictions, using AI', detail: 'AI-enabled algorithms predict the potential value of every outlet and product category to drive targeted, focused execution. Now live in 10 markets.', brand: 'Coca-Cola HBC' },
    ],
  },
  'slick-dms-features': {
    eyebrowLabel: 'NextGen DMS · Powered by AI',
    headingPre: 'Industry-first features,',
    headingAccent: 'built to guarantee uplift',
    lede: 'Beyond every core DMS module, AI DaaS adds capabilities you will not find anywhere else, across the four outcomes that move your business.',
    tabs: [
      { label: 'Sales & Distribution Up-lift', panelPre: 'Sales & Distribution', panelAccent: 'Up-lift', panelLede: 'AI that predicts demand, prevents stock-outs, and recommends every order so sell-out keeps climbing.', bandText: 'Minimum 3% sales uplift, guaranteed.', ctaLabel: 'Get a demo', ctaUrl: '/contact-us/' },
      { label: 'Working Capital Optimisation', panelPre: 'Working Capital', panelAccent: 'Optimisation', panelLede: 'Score credit, recover dues, and unlock channel financing so working capital keeps moving.', bandText: 'Faster cash cycles, fewer overdues.', ctaLabel: 'Get a demo', ctaUrl: '/contact-us/' },
      { label: 'Cost Optimisation', panelPre: 'Cost', panelAccent: 'Optimisation', panelLede: 'Run distribution leaner, with no dedicated operator, optimised routes, and zero wasted stock.', bandText: 'No DMS operator required.', ctaLabel: 'Get a demo', ctaUrl: '/contact-us/' },
      { label: 'Customer Service', panelPre: 'Customer', panelAccent: 'Service', panelLede: 'Turn service into numbers you can manage, from fill-rate to satisfaction at every outlet.', bandText: 'Service levels you can actually measure.', ctaLabel: 'Get a demo', ctaUrl: '/contact-us/' },
    ],
  },
  'slick-dms-comparison': {
    eyebrowLabel: 'Why DMS adoption is low',
    headingPre: 'Standard DMS is No Match for',
    headingAccent: 'NextGen DMS',
    headingSuffix: '',
    subtitle: 'Even after 20 years of evolution',
    oldLabel: 'Standard DMS',
    newLabel: 'NextGen DMS',
    oldRows: [
      { title: 'Monolithic architecture with complex workflows', sub: 'High-cost deployment, customization, and ongoing maintenance.' },
      { title: 'Old-world, complex UI/UX', sub: 'High training cost. Low adoption. Distributors push back.' },
      { title: 'High cost of operation', sub: 'Operator dependency makes DMS unviable for small distributors.' },
      { title: "Doesn't talk to accounting systems", sub: 'Duplicate work between DMS and books. Reconciliation pain.' },
    ],
    newRows: [
      { title: 'Composable architecture, NextGen stack', sub: 'Low-cost, quick deployment. Minimal maintenance overhead.' },
      { title: 'User-centered design, intuitive UI', sub: 'No training required. Quickest adoption in the category.' },
      { title: 'No DMS operator required. First time ever.', sub: 'AI nudges and prompts replace the operator entirely.' },
      { title: 'Native Tally and Zoho Books integration', sub: 'One source of truth. Multi-company operations supported.' },
    ],
  },
  'slick-dms-agents': {
    eyebrowLabel: 'Plug-in AI Agents',
    headingPre: 'An AI agent for every',
    headingAccent: 'DMS workflow',
    lede: 'Plug autonomous agents into your DMS to place orders, take orders, bill, and collect. Each one owns a specific part of the distribution workflow, so your team runs the exceptions, not the busywork.',
    agents: [
      { name: 'Primary Order Agent', lede: 'Places primary orders to the company so distributor stock is replenished on time.', benefits: ['Proactive replenishment that prevents out-of-stock.', 'Stock that stays accurate and on time.'] },
      { name: 'AI Order Agent', lede: "Calls mapped outlets and captures their orders on the distributor's behalf.", benefits: ['Secondary orders captured faster.', 'A steadier order flow from the market.'] },
      { name: 'AI Billing Agent', lede: 'Clears pending orders and runs billing, with credit and priority checks built in.', benefits: ['Faster, cleaner billing runs.', 'Credit risk caught before dispatch.'] },
      { name: 'AI Collection Agent', lede: 'Tracks outstanding payments and follows up with outlets automatically.', benefits: ['Reminders that go out on time, every time.', 'Lower outstanding and faster recovery.'] },
    ],
  },
  'slick-dms-faq': {
    heading: 'Frequently asked questions',
    faqs: [
      { q: "How does SalesCode's AI-powered DMS improve primary and secondary sales visibility?", a: "Traditional DMS platforms often stop at order capture. SalesCode's AI-powered DMS offers real-time visibility into primary and secondary sales, stock levels, and outlet performance by integrating directly with distributor operations and retail sell-out data. This eliminates blind spots, enabling better forecasting, replenishment, and promotion planning." },
      { q: "Can SalesCode's DMS handle complex distribution networks across multiple regions?", a: "Yes. It is built for multi-layered distribution ecosystems. Whether you're managing urban, rural, general trade, or modern trade distributors, the platform supports multiple hierarchies, multi-language interfaces, and region-specific pricing, making it ideal for emerging and mature markets alike." },
      { q: "What are the key AI capabilities that differentiate SalesCode's DMS from legacy systems?", a: "SalesCode's DMS uses AI to deliver intelligent stock recommendations, auto-replenishment suggestions, and anomaly detection (e.g. stockouts, fake invoices, delayed movement). Distributors and sales managers receive predictive insights that optimise fill rates, reduce manual errors, and improve working capital efficiency." },
      { q: "How quickly can we onboard distributors and sync SalesCode DMS with our ERP?", a: "SalesCode offers plug-and-play ERP integrations and distributor onboarding kits that minimise setup time. Most deployments go live in days, not months. It supports real-time API and flat-file syncs, enabling seamless data flow across ERP, SFA, and eB2B systems with minimal disruption to existing workflows." },
      { q: "Is SalesCode's DMS compliant with taxation, invoicing, and audit requirements?", a: "Absolutely. The system supports GST-compliant invoicing, credit/debit notes, e-way bill generation, and digital audit trails, making it fully ready for markets like India and the Middle East. It also includes access control, time-stamped logs, and digital signatures to meet internal compliance and external regulatory standards." },
    ],
  },
  'slick-dms-deploy-metrics': {
    headingAccent: 'Sales-Tech Deployment',
    headingRest: 'will never be the same',
    metrics: [
      { value: 90, unit: 'min', label: 'Data Integration' },
      { value: 3,  unit: 'hrs', label: 'Standard App Deployment' },
      { value: 4,  unit: 'hrs', label: 'ML Reco. Deployment' },
      { value: 24, unit: 'hrs', label: 'Enterprise App Deployment' },
    ],
  },
  'slick-dms-guarantee': {
    title: 'Better than any DMS, guaranteed',
    sub: 'Every feature of any DMS, plus NextGen UI/UX and unique features built to drive sales uplift. 110% refund if the technical success criteria are not met.',
  },
  'slick-dms-integrations': {
    eyebrowLabel: 'Accounting Integrations',
    headingPre: 'Compatible with',
    headingAccent: 'Tally and Zoho Books',
    lede: 'DMS syncs orders, invoices, and collections directly into your accounting software — no manual exports, no double-entry, no reconciliation headaches.',
    ctaLabel: 'Book a Demo',
    ctaUrl: '#',
  },
  'slick-dms-hero': {
    eyebrowLabel: 'AI Native DMS',
    headingPre: 'Distribution that',
    headingAccent: 'predicts',
    headingSuffix: ', not just records',
    subtitle: 'Legacy DMS only processes orders, and most still need a full-time operator to run. SalesCode predicts secondary demand, flags',
    subtitleBold: 'stock-outs before shelves go empty',
    ctaPlaceholder: 'Work email',
    ctaLabel: 'Request a Demo',
    ctaUrl: '#',
    trustItems: [
      { value: '3M+', label: 'orders / month' },
      { value: '5+', label: 'years at scale' },
      { value: 'No', label: 'operator required' },
      { value: '', label: 'Tally & Zoho ready' },
    ],
    planTitle: "Today's AI plan",
    planSub: 'Auto built for today',
    planRow1Key: 'Must order', planRow1Val: '6 brands',
    planRow2Key: 'Refill now', planRow2Val: '3 SKUs',
    planRow3Key: 'Cross-sell focus', planRow3Val: '+4 SKUs',
    agentName: 'SCAI Agent',
    agentMsgPre: 'Hi Rajesh, these 2 actions will',
    agentMsgBold: 'lift fill rate by 6%',
    agentMsgPost: 'at Sharma Distributors this week.',
  },
  'slick-sc-trust-metrics': {
    headingPre: 'Scale you can',
    headingGradient: 'count on',
    headingSuffix: '',
    subtitle: 'Leading brands, dozens of markets, millions of users — the scale behind every order placed on SalesCode.',
    stats: [
      { target: 65, suffix: '+',  label: 'Global Brands' },
      { target: 18, suffix: '+',  label: 'Countries'     },
      { target: 3,  suffix: 'M+', label: 'Users'         },
      { target: 1,  suffix: 'B+', label: 'Transactions'  },
    ],
  },
  'slick-sc-customer-stories': {
    eyebrowLabel: 'Customer Success Stories',
    headingPre: "CPG Leaders' Experience with",
    headingAccent: 'SalesCode.ai',
    subtitle: 'Real outcomes from the CPG teams running their route-to-market on SalesCode.',
    stories: [
      {
        id: 'coca-cola-gccb',
        brandName: 'Coca-Cola GCCB',
        brandColor: '#E61A27',
        categoryLabel: 'Retail Execution',
        title: 'Coca-Cola GCCB Accelerated Retail Execution Across Regions',
        description: 'AI-led execution tasks and real-time visibility helped field teams lift store level compliance and coverage across multiple markets.',
        speakerInitials: 'AM',
        speakerName: 'Akeel Mohamed',
        speakerRole: 'Ex CEO & Managing Director, Coca-Cola GCCB',
        storyUrl: '',
      },
      {
        id: 'marico',
        brandName: 'marico',
        brandColor: '#1B3A6B',
        categoryLabel: 'Sales Productivity',
        title: 'How Marico Improved Sales Team Productivity by 37%',
        description: 'Hyper-personalized targets and instant incentives reshaped daily rep behaviour, driving measurable gains in productivity and focus distribution.',
        speakerInitials: 'VS',
        speakerName: 'Vivek Shah',
        speakerRole: 'Sales Transformation, Ecom & New GTM Head, Marico',
        storyUrl: '',
      },
      {
        id: 'apollo-tyres',
        brandName: 'APOLLO',
        brandColor: '#4A2A82',
        categoryLabel: 'Customer Service',
        title: 'Apollo Tyres Strengthened Dealer Service and Coverage',
        description: 'Unified order, pricing and service workflows gave the team a single view of the dealer network and faster response on the ground.',
        speakerInitials: 'AC',
        speakerName: 'Aneet Chaku',
        speakerRole: 'Head of Customer Service, Apollo Tyres',
        storyUrl: '',
      },
      {
        id: 'emami',
        brandName: 'emami',
        brandColor: '#0E7C42',
        categoryLabel: 'Sales Development',
        title: 'Emami Scaled Field Execution Across the National Network',
        description: 'A smarter SFA layer turned everyday rep actions into guided, high value steps, supporting consistent execution at national scale.',
        speakerInitials: 'MS',
        speakerName: 'Malay Shah',
        speakerRole: 'Head, National Sales Development, Emami Ltd',
        storyUrl: '',
      },
    ],
    ctaLabel: 'View All Success Stories',
    ctaUrl: '#all-stories',
  },
  'slick-sc-brand-strip': {
    eyebrowLabel: 'Trusted Across Industries',
    headingPre: 'Trusted by',
    headingGradient: 'leading enterprises',
    headingSuffix: 'in India and around the world',
    subtitle: 'From FMCG to pharma, top brands count on SalesCode to transform their route-to-market execution.',
    logos: [
      { imageUrl: '', alt: 'AlSafi Danone' },
      { imageUrl: '', alt: 'Aujan Coca-Cola' },
      { imageUrl: '', alt: 'Havells' },
      { imageUrl: '', alt: 'Heritage Foods' },
      { imageUrl: '', alt: 'Zydus Wellness' },
      { imageUrl: '', alt: 'Godrej' },
      { imageUrl: '', alt: 'Emami' },
    ],
    ctaLabel: 'See All Clients',
    ctaUrl: '#clients',
    ctaNote: 'Join 65+ global brands transforming their sales operations.',
  },
  'slick-sc-video-showcase': {
    eyebrowLabel: 'SalesCode Experience Center',
    headingPre: 'See the Code of',
    headingGradient: 'Future-Ready',
    headingSuffix: 'Sales and Trade',
    subtitle: 'Watch how SalesCode unifies SFA, DMS, eB2B and AI sales agents into one AI-native route-to-market platform, deployed in just three clicks.',
    barLabel: 'salescode.ai / Platform Walkthrough',
    caption: 'Inside the AI-native route-to-market platform',
    thumbnailUrl: '',
    videoUrl: '',
    ctaLabel: 'Watch the Demo',
    ctaUrl: '#demo',
    ctaNote: 'A 2 minute look at SFA, DMS, eB2B and AI sales agents in action.',
  },
  'slick-scai-whatsapp-agent': {
    headingAccent: 'WhatsApp',
    headingWhite: 'Agent',
    taglineAccent: 'End-to-end 100% order flow from WhatsApp',
    taglineRest: ' itself - faster and simpler ordering, available 24x7.',
    bullets: [
      { text: 'Order via handwritten notes, voice notes, or simple chat', highlight: 'handwritten notes, voice notes, or simple chat' },
      { text: 'Multilingual support across 30+ languages', highlight: '30+ languages' },
      { text: 'Integrated with your existing order systems', highlight: 'existing order systems' },
      { text: 'Promo and pricing logic, same as voice agent', highlight: 'Promo and pricing logic' },
    ],
    languages: [
      { label: 'English', flag: '🇬🇧', thumbnailUrl: '' },
      { label: 'Hindi',   flag: '🇮🇳', thumbnailUrl: '' },
    ],
    primaryCtaLabel: 'Experience in 3 Clicks!',
    primaryCtaUrl: '#',
    ghostCtaLabel: 'Contact Sales',
    ghostCtaUrl: '#',
  },
  'slick-scai-global-showcase': {
    headingWhite: 'Global Showcase of',
    headingAccent: 'SCAI',
    panels: [
      { thumbnailUrl: '', alt: 'Global Coke showcase' },
      { thumbnailUrl: '', alt: 'Global P&G showcase' },
    ],
  },
  'slick-scai-human-test': {
    headingAccent1: 'SCAI',
    headingMid: 'Passes',
    headingAccent2: 'the Human Test !!',
    subheading: 'Across Geographies and Languages',
    clips: [
      { thumbnailUrl: '' },
      { thumbnailUrl: '' },
      { thumbnailUrl: '' },
    ],
    humanTestPercent: '100%',
    statDescNormal: 'Of the Retailers',
    statDescBold: 'thought they',
    statDescItalicAccent: 'talking to a human',
    metrics: [
      { label: 'Call ', labelBold: 'Pickup', value: '54%+' },
      { label: '',      labelBold: 'Order',  value: '24%+' },
    ],
    primaryCtaLabel: 'Experience in 3 Clicks!',
    primaryCtaUrl: '#',
  },
  'slick-scai-industry': {
    headingWhite: 'AI Sales Agents for',
    headingAccent: 'Every Business',
    categories: [
      { label: 'Beverages',        icon: 'cupSoda'   },
      { label: 'Snacks',           icon: 'cookie'    },
      { label: 'Dairy',            icon: 'milk'      },
      { label: 'Confectionary',    icon: 'candy'     },
      { label: 'Personal Care',    icon: 'sparkles'  },
      { label: 'Hardware',         icon: 'wrench'    },
      { label: 'OTC Drugs',        icon: 'pill'      },
      { label: 'Staples & Grains', icon: 'wheat'     },
      { label: 'Frozen Foods',     icon: 'snowflake' },
      { label: 'Bakery & Fresh',   icon: 'croissant' },
    ],
    primaryCtaLabel: 'Experience in 3 Clicks!',
    primaryCtaUrl: '#',
    ghostCtaLabel: 'Contact Sales',
    ghostCtaUrl: '#',
  },
  'slick-scai-quick-guide': {
    headingPre: 'Experience in',
    headingAccent: '3 clicks',
    headingMid: '& Build for Your',
    headingBold: 'Enterprise',
    steps: [
      { label: 'STEP 1', title: 'Tell us about your business' },
      { label: 'STEP 2', title: 'Add the products you want to sell' },
      { label: 'STEP 3', title: 'Watch your agent take a real order' },
    ],
    primaryCtaLabel: 'Experience in 3 Clicks!',
    primaryCtaUrl: '#',
    ghostCtaLabel: 'Contact Sales',
    ghostCtaUrl: '#',
    thumbnailUrl: '',
    videoCaption: "See exactly what you'll be setting up",
  },
  'slick-scai-revenue': {
    headingLine1: 'Your Sales Team is losing revenue.',
    headingAccent: 'Every Day.',
    salesLossPercent: 33,
    metrics: [
      { value: '30%+',   label: "of field force can't sell the full range",   impact: '-9%',  icon: 'truck' },
      { value: '10-15%', label: 'of outlets skipped every day',               impact: '-7%',  icon: 'map'   },
      { value: '35-40%', label: 'avg attrition. 6 months to ramp new hires',  impact: '-10%', icon: 'userX' },
      { value: '8-12%',  label: 'field absent daily. Territories go dark',    impact: '-7%',  icon: 'ban'   },
    ],
  },
  'slick-scai-pilot': {
    headingAccent: 'Results',
    headingRest: 'with SCAI',
    subtext: 'Results across enterprise deployments. Onboarded retailers consistently outperform on every KPI.',
    metrics: [
      { value: '35-50%', label: 'Call Pick-Up Rate',     comparison: 'vs 10-20%',     comparedTo: 'with Human', icon: 'callPickup'      },
      { value: '40-50%', label: 'Engagement Rate',        comparison: 'vs 20-30%',     comparedTo: 'with Human', icon: 'engagement'      },
      { value: '15-25%', label: 'Order Conversion',       comparison: 'vs <5%',         comparedTo: 'with Human', icon: 'orderConversion' },
      { value: '25%+',   label: 'Repeat Call Order Rate', comparison: 'vs Not Tracked', comparedTo: 'with Human', icon: 'repeatCall'      },
    ],
  },
  'slick-scai-hero': {
    headingLine1: 'AI Sales Agent That',
    typedPhrases: ['Is Never Absent!', 'Works 24x7', 'Makes Perfect Calls From Day 1'],
    badgeLabel: 'AI Sales Agent for CPG Sales',
    bodyBold: 'Enterprise-ready AI Sales Agent',
    body: 'that integrate with your SFA, DMS, eB2B, ERP & existing systems to automate order taking, retailer engagement, & sales workflows at scale.',
    primaryCtaLabel: 'Experience in 3 Clicks!',
    primaryCtaUrl: '#',
    ghostCtaLabel: 'Contact Sales',
    ghostCtaUrl: '#',
    creditsLabel: 'Create An Account And Get',
    creditsHighlight: '₹500 Credits FREE',
    avatarUrl: '',
    avatarCaptionAccent: 'SCAI',
    avatarCaptionMain: 'Sells Better',
    avatarCaptionSuffix: 'than',
    avatarCaptionDanger: 'Humans',
  },
  'slick-footer-complex': {
    brandName: "Atlas",
    tagline: "The workspace where modern product teams plan, build, and ship together.",
    columns: [
      { title: "Product", links: [{ label: "Features", href: "#" }, { label: "Pricing", href: "#" }, { label: "Changelog", href: "#" }, { label: "Roadmap", href: "#" }] },
      { title: "Company", links: [{ label: "About", href: "#" }, { label: "Blog", href: "#" }, { label: "Careers", href: "#" }, { label: "Press", href: "#" }] },
      { title: "Resources", links: [{ label: "Docs", href: "#" }, { label: "API", href: "#" }, { label: "Status", href: "#" }, { label: "Security", href: "#" }] },
    ],
    socials: [
      { name: "twitter", href: "#" },
      { name: "github", href: "#" },
      { name: "linkedin", href: "#" },
    ],
    newsletterHeading: "Get the monthly dispatch",
    newsletterSubtext: "Product updates and engineering deep-dives, once a month. No spam.",
    newsletterPlaceholder: "you@company.com",
    newsletterCtaLabel: "Subscribe →",
    copyright: "© 2025 Atlas Labs, Inc. All rights reserved.",
    giantBrandWord: "Atlas",
  },
  'slick-eb2b-hero': {
    pillText: 'Guaranteed 3%-5% Sales Uplift',
    headingPre: 'The eB2B platform that',
    headingGrad: 'closes every sale',
    headingPost: '',
    sub: 'AI-powered direct-to-retailer ordering with intelligent basket building, NPD push, and promo execution — all in one app.',
    subBold: 'guaranteed 3%–5% sales uplift.',
    ctaLabel: 'Book a Demo',
    ctaUrl: '#demo',
    ctaGhostLabel: 'Watch Video',
    ctaGhostUrl: '#',
    trustText: 'Trusted by 65+ global CPG brands',
  },
  'slick-eb2b-scale': {
    eyebrow: 'Platform Scale',
    headingPre: "World's ",
    headingGrad: 'No.1 eB2B Platform',
    stats: [
      { num: '3M+', label: 'Active Users' },
      { num: '18+', label: 'Countries' },
      { num: '1B+', label: 'Transactions' },
      { num: '65+', label: 'Top CPG Brands' },
    ],
  },
  'slick-eb2b-why': {
    eyebrow: 'Why Top CPG Companies Choose SalesCode',
    headingPre: "World's ",
    headingGrad1: 'First',
    headingMid: ' and Most Advanced ',
    headingGrad2: 'eB2B SaaS Platform',
    sub: 'Our proprietary AI/ML engine delivers a guaranteed 3% to 5% sales uplift through higher product distribution, increased order values, and recovery of lost sales opportunities.',
    ctaLabel: 'Book a Demo →',
    ctaUrl: '#demo',
  },
  'slick-eb2b-features': {
    eyebrow: 'Platform Capabilities',
    headingPre: 'Built for ',
    headingGrad: 'Every Sales Moment',
  },
  'slick-eb2b-integrations': {
    pillText: "'Plug-In Anything' and 'Plug Into Anything'",
    headingPre: 'Intelligent ',
    headingGrad: 'Integrations & Plug-Ins',
    sub: 'Quick integration with SFA, DMS and third party plug-ins for IR, IM, Loyalty, Wallet, Payment, Lending and others to drive a fully connected eB2B ecosystem.',
  },
  'slick-eb2b-impact': {
    eyebrow: 'Proven Impact',
    headingPre: 'Numbers that prove the ',
    headingGrad: 'Sales Uplift',
  },
  'slick-eb2b-deployments': {
    eyebrow: 'Our Deployments',
    headingPre: 'Trusted by ',
    headingGrad: 'Industry Leaders',
    sub: "From Coca-Cola to Colgate, the world's top CPG brands run their eB2B operations on SalesCode.",
    ctaLabel: 'View Case Studies →',
    ctaUrl: '#case-studies',
  },
  'slick-ab-hero': {
    eyebrow: 'About SalesCode.ai',
    headingPre: 'The AI Company',
    headingGrad: 'Guaranteeing',
    headingPost: 'Your Sales Uplift',
    sub: 'Born in CPG. Built for scale. Proven across 18+ countries and 65+ global brands.',
  },
  'slick-ab-founder-banner': {
    headingPre: 'Trusted by ',
    headingBold: '65+ Brands',
    headingPost: ' across the globe',
    sub: 'From Fortune 500 giants to regional powerhouses — they all trust SalesCode.',
  },
  'slick-ab-stats': {
    stats: [
      { num: '200+', label: 'Team Members', sub: 'Across Sales, Tech & AI' },
      { num: '65+', label: 'Global Brands', sub: 'Top CPG Companies' },
      { num: '18+', label: 'Countries', sub: 'Global Footprint' },
      { num: '1B+', label: 'Transactions', sub: 'Processed Annually' },
    ],
  },
  'slick-ab-story': {
    eyebrow: 'Our Story',
    headingPre: 'From the field',
    headingGrad: 'to the future',
    p1: 'SalesCode.ai was founded in 2014 by <strong>Ranjeet Kumar</strong>, a seasoned CPG veteran with 27+ years at companies like Hindustan Coca-Cola Beverages, and <strong>Madhusudan Atmakuri</strong>, an enterprise technology expert with 27+ years of experience.',
    p2: 'Having lived the challenges of CPG sales first-hand, they knew the industry needed more than incremental improvements. It needed an <strong>AI-first platform</strong> that could guarantee outcomes.',
    p3: 'Today, SalesCode.ai powers the sales operations of 65+ global brands across 18+ countries, processing over 1 billion transactions annually.',
    quoteText: "We didn't just build a platform — we built the future of CPG sales. Every feature exists because we've lived the problem.",
    quoteAuthorName: 'Ranjeet Kumar',
    quoteAuthorTitle: 'CEO & Co-Founder, SalesCode.ai',
    quoteAuthorInitials: 'RK',
  },
  'slick-ab-video': {
    videoUrl: 'https://salescode.ai/wp-content/uploads/2025/09/experience-center-vid-for-website-video2.mp4',
    ariaLabel: 'SalesCode.ai Experience Center walkthrough',
  },
  'slick-ab-awards': {
    eyebrow: 'Recognition',
    heading: 'The world recognises us.',
  },
  'slick-ab-founders': {
    eyebrow: 'The Team',
    heading: 'Founded by sales and tech experts.',
    sub: 'Every co-founder has lived the problem they are solving. Decades in CPG sales and enterprise technology, now building the answer together.',
  },
  'slick-ab-investors': {
    eyebrow: 'Investors & Advisors',
    heading: 'Backed by the best.',
    sub: 'Marquee investors and advisors with deep CPG, technology and venture expertise across India and globally.',
  },
  'slick-ab-cta': {
    heading: 'Ready to guarantee your sales uplift?',
    sub: 'Join 65+ leading CPG brands. Book a personalised demo with our team.',
    ctaLabel: 'Book a Demo',
    ctaUrl: '#demo',
  },
  'slick-offices': {
    eyebrow: 'Offices & Partners',
    headingLine1: 'Our Offices Are',
    headingLine2Pre: 'Around The ',
    headingLine2Grad: 'World',
    linkedinUrl: 'https://www.linkedin.com/company/salescode-ai/',
  },
  'slick-lets-talk': {
    eyebrow: 'Get Started',
    headingPre: "Let's ",
    headingGrad: 'Talk',
    sub: "From first conversation to measurable sales uplift in five clear steps. Welcome to The New '",
    ctaLabel: 'Book a Demo',
    ctaUrl: '#demo',
  },
  'slick-sc-navbar': {
    ctaLabel: 'Book a Demo',
    ctaUrl: '#book-a-demo',
  },
  'slick-sc-footer': {
    ctaEyebrow: 'Sales Uplift Guaranteed',
    ctaHeadingPre: 'The new ',
    ctaHeadingGrad: "'CODE'",
    ctaHeadingPost: ' of CPG sales.',
    ctaSub: '3% minimum uplift, contractually guaranteed. 110% refund clause if unmet.',
    ctaLabel: 'Get a Demo',
    ctaUrl: '#book-a-demo',
    email: 'business@salescode.ai',
    phone: '1800 212 8898',
    phoneHours: 'Mon to Fri · 10:00 to 19:00 IST',
    linkedinUrl: 'https://www.linkedin.com/company/salescode-ai/',
    xUrl: '#',
    instagramUrl: '#',
    youtubeUrl: '#',
    facebookUrl: '#',
    copyright: '© 2026 Applicate IT Solutions Pvt. Ltd. All rights reserved.',
  },
  'slick-contact': {
    eyebrow: 'Contact & Demo',
    headingPre: "Let's quantify the ",
    headingGrad: 'sales uplift',
    headingPost: ' we can deliver for you.',
    lede: 'Tell us about your route to market, or pick a slot to see SalesCode.ai live. A sales tech specialist will respond within one business day.',
    email: 'hello@salescode.ai',
    phone: '+91 99 9999 9999',
    hq: 'Gurugram, India',
    regionalOffices: 'LATAM, MENA, SEA, Africa',
  },
};
